import * as stylex from '@stylexjs/stylex';
import { color } from './color.stylex';

// A constant can be used to avoid repeating the media query
const [DARK] = '@media (prefers-color-scheme: dark)';

export const tokens = stylex.defineVars({
  'fds-black': { default: '#000000', [DARK]: '#000000' },
  'fds-black-alpha-05': {
    default: 'rgba(0, 0, 0, 0.05)',
    [DARK]: 'rgba(0, 0, 0, 0.05)',
  },
  'fds-black-alpha-10': {
    default: 'rgba(0, 0, 0, 0.1)',
    [DARK]: 'rgba(0, 0, 0, 0.1)',
  },
  'fds-black-alpha-15': {
    default: 'rgba(0, 0, 0, 0.15)',
    [DARK]: 'rgba(0, 0, 0, 0.15)',
  },
  'fds-black-alpha-20': {
    default: 'rgba(0, 0, 0, 0.2)',
    [DARK]: 'rgba(0, 0, 0, 0.2)',
  },
  'fds-black-alpha-30': {
    default: 'rgba(0, 0, 0, 0.3)',
    [DARK]: 'rgba(0, 0, 0, 0.3)',
  },
  'fds-black-alpha-40': {
    default: 'rgba(0, 0, 0, 0.4)',
    [DARK]: 'rgba(0, 0, 0, 0.4)',
  },
  'fds-black-alpha-50': {
    default: 'rgba(0, 0, 0, 0.5)',
    [DARK]: 'rgba(0, 0, 0, 0.5)',
  },
  'fds-black-alpha-60': {
    default: 'rgba(0, 0, 0, 0.6)',
    [DARK]: 'rgba(0, 0, 0, 0.6)',
  },
  'fds-black-alpha-80': {
    default: 'rgba(0, 0, 0, 0.8)',
    [DARK]: 'rgba(0, 0, 0, 0.8)',
  },
  'fds-blue-05': { default: '#ECF3FF', [DARK]: '#ECF3FF' },
  'fds-blue-30': { default: '#AAC9FF', [DARK]: '#AAC9FF' },
  'fds-blue-40': { default: '#77A7FF', [DARK]: '#77A7FF' },
  'fds-blue-60': { default: '#1877F2', [DARK]: '#1877F2' },
  'fds-blue-70': { default: '#2851A3', [DARK]: '#2851A3' },
  'fds-blue-80': { default: '#1D3C78', [DARK]: '#1D3C78' },
  'fds-button-text': { default: '#444950', [DARK]: '#444950' },
  'fds-comment-background': { default: '#F2F3F5', [DARK]: '#F2F3F5' },
  'fds-dark-mode-gray-35': { default: '#CCCCCC', [DARK]: '#CCCCCC' },
  'fds-dark-mode-gray-50': { default: '#828282', [DARK]: '#828282' },
  'fds-dark-mode-gray-70': { default: '#4A4A4A', [DARK]: '#4A4A4A' },
  'fds-dark-mode-gray-80': { default: '#373737', [DARK]: '#373737' },
  'fds-dark-mode-gray-90': { default: '#282828', [DARK]: '#282828' },
  'fds-dark-mode-gray-100': { default: '#1C1C1C', [DARK]: '#1C1C1C' },
  'fds-gray-00': { default: '#F5F6F7', [DARK]: '#F5F6F7' },
  'fds-gray-05': { default: '#F2F3F5', [DARK]: '#F2F3F5' },
  'fds-gray-10': { default: '#EBEDF0', [DARK]: '#EBEDF0' },
  'fds-gray-20': { default: '#DADDE1', [DARK]: '#DADDE1' },
  'fds-gray-25': { default: '#CCD0D5', [DARK]: '#CCD0D5' },
  'fds-gray-30': { default: '#BEC3C9', [DARK]: '#BEC3C9' },
  'fds-gray-45': { default: '#8D949E', [DARK]: '#8D949E' },
  'fds-gray-70': { default: '#606770', [DARK]: '#606770' },
  'fds-gray-80': { default: '#444950', [DARK]: '#444950' },
  'fds-gray-90': { default: '#303338', [DARK]: '#303338' },
  'fds-gray-100': { default: '#1C1E21', [DARK]: '#1C1E21' },
  'fds-green-55': { default: '#00A400', [DARK]: '#00A400' },
  'fds-highlight': { default: '#3578E5', [DARK]: '#3578E5' },
  'fds-highlight-cell-background': { default: '#ECF3FF', [DARK]: '#ECF3FF' },
  'fds-primary-icon': { default: '#1C1E21', [DARK]: '#1C1E21' },
  'fds-primary-text': { default: '#1C1E21', [DARK]: '#1C1E21' },
  'fds-red-55': { default: '#FA383E', [DARK]: '#FA383E' },
  'fds-soft': {
    default: 'cubic-bezier(.08,.52,.52,1)',
    [DARK]: 'cubic-bezier(.08,.52,.52,1)',
  },
  'fds-spectrum-aluminum-tint-70': { default: '#E4F0F6', [DARK]: '#E4F0F6' },
  'fds-spectrum-blue-gray-tint-70': { default: '#CFD1D5', [DARK]: '#CFD1D5' },
  'fds-spectrum-cherry': { default: '#F35369', [DARK]: '#F35369' },
  'fds-spectrum-cherry-tint-70': { default: '#FBCCD2', [DARK]: '#FBCCD2' },
  'fds-spectrum-grape-tint-70': { default: '#DDD5F0', [DARK]: '#DDD5F0' },
  'fds-spectrum-grape-tint-90': { default: '#F4F1FA', [DARK]: '#F4F1FA' },
  'fds-spectrum-lemon-dark-1': { default: '#F5C33B', [DARK]: '#F5C33B' },
  'fds-spectrum-lemon-tint-70': { default: '#FEF2D1', [DARK]: '#FEF2D1' },
  'fds-spectrum-lime': { default: '#A3CE71', [DARK]: '#A3CE71' },
  'fds-spectrum-lime-tint-70': { default: '#E4F0D5', [DARK]: '#E4F0D5' },
  'fds-spectrum-orange-tint-70': { default: '#FCDEC5', [DARK]: '#FCDEC5' },
  'fds-spectrum-orange-tint-90': { default: '#FEF4EC', [DARK]: '#FEF4EC' },
  'fds-spectrum-seafoam-tint-70': { default: '#CAEEF9', [DARK]: '#CAEEF9' },
  'fds-spectrum-slate-dark-2': { default: '#89A1AC', [DARK]: '#89A1AC' },
  'fds-spectrum-slate-tint-70': { default: '#EAEFF2', [DARK]: '#EAEFF2' },
  'fds-spectrum-teal': { default: '#6BCEBB', [DARK]: '#6BCEBB' },
  'fds-spectrum-teal-dark-1': { default: '#4DBBA6', [DARK]: '#4DBBA6' },
  'fds-spectrum-teal-dark-2': { default: '#31A38D', [DARK]: '#31A38D' },
  'fds-spectrum-teal-tint-70': { default: '#D2F0EA', [DARK]: '#D2F0EA' },
  'fds-spectrum-teal-tint-90': { default: '#F0FAF8', [DARK]: '#F0FAF8' },
  'fds-spectrum-tomato': { default: '#FB724B', [DARK]: '#FB724B' },
  'fds-spectrum-tomato-tint-30': { default: '#F38E7B', [DARK]: '#F38E7B' },
  'fds-spectrum-tomato-tint-90': { default: '#FDEFED', [DARK]: '#FDEFED' },
  'fds-strong': {
    default: 'cubic-bezier(.12,.8,.32,1)',
    [DARK]: 'cubic-bezier(.12,.8,.32,1)',
  },
  'fds-white': { default: '#FFFFFF', [DARK]: '#FFFFFF' },
  'fds-white-alpha-05': {
    default: 'rgba(255, 255, 255, 0.05)',
    [DARK]: 'rgba(255, 255, 255, 0.05)',
  },
  'fds-white-alpha-10': {
    default: 'rgba(255, 255, 255, 0.1)',
    [DARK]: 'rgba(255, 255, 255, 0.1)',
  },
  'fds-white-alpha-20': {
    default: 'rgba(255, 255, 255, 0.2)',
    [DARK]: 'rgba(255, 255, 255, 0.2)',
  },
  'fds-white-alpha-30': {
    default: 'rgba(255, 255, 255, 0.3)',
    [DARK]: 'rgba(255, 255, 255, 0.3)',
  },
  'fds-white-alpha-40': {
    default: 'rgba(255, 255, 255, 0.4)',
    [DARK]: 'rgba(255, 255, 255, 0.4)',
  },
  'fds-white-alpha-50': {
    default: 'rgba(255, 255, 255, 0.5)',
    [DARK]: 'rgba(255, 255, 255, 0.5)',
  },
  'fds-white-alpha-60': {
    default: 'rgba(255, 255, 255, 0.6)',
    [DARK]: 'rgba(255, 255, 255, 0.6)',
  },
  'fds-white-alpha-80': {
    default: 'rgba(255, 255, 255, 0.8)',
    [DARK]: 'rgba(255, 255, 255, 0.8)',
  },
  'fds-yellow-20': { default: '#FFBA00', [DARK]: '#FFBA00' },
  // accent: { default: '#1763CF', [DARK]: '#1763CF' },
  'always-white': { default: '#FFFFFF', [DARK]: '#FFFFFF' },
  'always-black': { default: 'black', [DARK]: 'black' },
  'always-dark-gradient': {
    default: 'linear-gradient(rgba(0,0,0,0), rgba(0,0,0,0.6))',
    [DARK]: 'linear-gradient(rgba(0,0,0,0), rgba(0,0,0,0.6))',
  },
  'always-dark-overlay': {
    default: 'rgba(0, 0, 0, 0.4)',
    [DARK]: 'rgba(0, 0, 0, 0.4)',
  },
  'always-light-overlay': {
    default: 'rgba(255, 255, 255, 0.4)',
    [DARK]: 'rgba(255, 255, 255, 0.4)',
  },
  'always-gray-40': { default: '#65676B', [DARK]: '#65676B' },
  'always-gray-75': { default: '#BCC0C4', [DARK]: '#BCC0C4' },
  'always-gray-95': { default: '#F0F2F5', [DARK]: '#F0F2F5' },
  'attachment-footer-background': { default: '#F0F2F5', [DARK]: '#F0F2F5' },
  'background-deemphasized': { default: '#F0F2F5', [DARK]: '#F0F2F5' },
  'badge-background-color-blue': {
    default: color.accent, // 'var(--accent)',
    [DARK]: color.accent, // 'var(--accent)',
  },
  'badge-background-color-dark-gray': {
    default: color['secondary-icon'], // 'var(--secondary-icon)',
    [DARK]: color['secondary-icon'], // 'var(--secondary-icon)',
  },
  'badge-background-color-gray': {
    default: color['disabled-icon'], // 'var(--disabled-icon)',
    [DARK]: color['disabled-icon'], // 'var(--disabled-icon)',
  },
  'badge-background-color-green': {
    default: color.positive, // 'var(--positive)',
    [DARK]: color.positive, // 'var(--positive)',
  },
  'badge-background-color-light-blue': {
    default: color['highlight-bg'], // 'var(--highlight-bg)',
    [DARK]: color['highlight-bg'], // 'var(--highlight-bg)',
  },
  'badge-background-color-red': {
    default: color['notification-badge'], //  'var(--notification-badge)',
    [DARK]: color['notification-badge'], // 'var(--notification-badge)',
  },
  'badge-background-color-yellow': {
    default: color['base-lemon'], // 'var(--base-lemon)',
    [DARK]: color['base-lemon'], // 'var(--base-lemon)',
  },
  'base-blue': { default: '#1877F2', [DARK]: '#1877F2' },
  'base-cherry': { default: '#F3425F', [DARK]: '#F3425F' },
  'base-grape': { default: '#9360F7', [DARK]: '#9360F7' },
  // 'base-lemon': { default: '#F7B928', [DARK]: '#F7B928' },
  'base-lime': { default: '#45BD62', [DARK]: '#45BD62' },
  'base-pink': { default: '#FF66BF', [DARK]: '#FF66BF' },
  'base-seafoam': { default: '#54C7EC', [DARK]: '#54C7EC' },
  'base-teal': { default: '#2ABBA7', [DARK]: '#2ABBA7' },
  'base-tomato': { default: '#FB724B', [DARK]: '#FB724B' },
  'text-badge-info-background': {
    default: 'hsl(214, 89%, 52%)',
    [DARK]: 'hsl(214, 89%, 52%)',
  },
  'text-badge-success-background': { default: '#31A24C', [DARK]: '#31A24C' },
  'text-badge-attention-background': {
    default: 'hsl(40, 89%, 52%)',
    [DARK]: 'hsl(40, 89%, 52%)',
  },
  'text-badge-critical-background': { default: '#e41e3f', [DARK]: '#e41e3f' },
  'blue-link': { default: '#216FDB', [DARK]: '#216FDB' },
  'border-focused': { default: '#65676B', [DARK]: '#65676B' },
  'card-background': { default: '#FFFFFF', [DARK]: '#FFFFFF' },
  'card-background-flat': { default: '#F7F8FA', [DARK]: '#F7F8FA' },
  'comment-background': { default: '#F0F2F5', [DARK]: '#F0F2F5' },
  'comment-footer-background': { default: '#F6F9FA', [DARK]: '#F6F9FA' },
  'dataviz-primary-1': {
    default: 'rgb(48,200,180)',
    [DARK]: 'rgb(48,200,180)',
  },
  'disabled-button-background': { default: '#E4E6EB', [DARK]: '#E4E6EB' },
  'disabled-button-text': { default: '#BCC0C4', [DARK]: '#BCC0C4' },
  // 'disabled-icon': { default: '#BCC0C4', [DARK]: '#BCC0C4' },
  'disabled-text': { default: '#BCC0C4', [DARK]: '#BCC0C4' },
  divider: { default: '#CED0D4', [DARK]: '#CED0D4' },
  'event-date': { default: '#F3425F', [DARK]: '#F3425F' },
  'fb-wordmark': { default: '#0866FF', [DARK]: '#0866FF' },
  'fb-logo': { default: '#0866FF', [DARK]: '#0866FF' },
  'filter-accent': {
    default:
      'invert(39%) sepia(57%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(147.75%) hue-rotate(202deg) brightness(97%) contrast(96%)',
    [DARK]:
      'invert(39%) sepia(57%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(147.75%) hue-rotate(202deg) brightness(97%) contrast(96%)',
  },
  'filter-always-white': { default: 'invert(100%)', [DARK]: 'invert(100%)' },
  'filter-disabled-icon': {
    default:
      'invert(80%) sepia(6%) saturate(200%) saturate(120%) hue-rotate(173deg) brightness(98%) contrast(89%)',
    [DARK]:
      'invert(80%) sepia(6%) saturate(200%) saturate(120%) hue-rotate(173deg) brightness(98%) contrast(89%)',
  },
  'filter-placeholder-icon': {
    default:
      'invert(59%) sepia(11%) saturate(200%) saturate(135%) hue-rotate(176deg) brightness(96%) contrast(94%)',
    [DARK]:
      'invert(59%) sepia(11%) saturate(200%) saturate(135%) hue-rotate(176deg) brightness(96%) contrast(94%)',
  },
  'filter-primary-accent': {
    default:
      'invert(39%) sepia(57%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(147.75%) hue-rotate(202deg) brightness(97%) contrast(96%)',
    [DARK]:
      'invert(39%) sepia(57%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(147.75%) hue-rotate(202deg) brightness(97%) contrast(96%)',
  },
  'filter-primary-icon': {
    default:
      'invert(8%) sepia(10%) saturate(200%) saturate(200%) saturate(166%) hue-rotate(177deg) brightness(104%) contrast(91%)',
    [DARK]:
      'invert(8%) sepia(10%) saturate(200%) saturate(200%) saturate(166%) hue-rotate(177deg) brightness(104%) contrast(91%)',
  },
  'filter-secondary-icon': {
    default:
      'invert(39%) sepia(21%) saturate(200%) saturate(109.5%) hue-rotate(174deg) brightness(94%) contrast(86%)',
    [DARK]:
      'invert(39%) sepia(21%) saturate(200%) saturate(109.5%) hue-rotate(174deg) brightness(94%) contrast(86%)',
  },
  'filter-warning-icon': {
    default:
      'invert(77%) sepia(29%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(128%) hue-rotate(359deg) brightness(102%) contrast(107%)',
    [DARK]:
      'invert(77%) sepia(29%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(128%) hue-rotate(359deg) brightness(102%) contrast(107%)',
  },
  'filter-blue-link-icon': {
    default:
      'invert(30%) sepia(98%) saturate(200%) saturate(200%) saturate(200%) saturate(166.5%) hue-rotate(192deg) brightness(91%) contrast(101%)',
    [DARK]:
      'invert(30%) sepia(98%) saturate(200%) saturate(200%) saturate(200%) saturate(166.5%) hue-rotate(192deg) brightness(91%) contrast(101%)',
  },
  'filter-positive': {
    default:
      'invert(37%) sepia(61%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(115%) hue-rotate(91deg) brightness(97%) contrast(105%)',
    [DARK]:
      'invert(37%) sepia(61%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(115%) hue-rotate(91deg) brightness(97%) contrast(105%)',
  },
  'filter-negative': {
    default:
      'invert(25%) sepia(33%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(110%) hue-rotate(345deg) brightness(132%) contrast(96%)',
    [DARK]:
      'invert(25%) sepia(33%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(110%) hue-rotate(345deg) brightness(132%) contrast(96%)',
  },
  'focus-ring-blue': { default: '#1877F2', [DARK]: '#1877F2' },
  'glimmer-spinner-icon': { default: '#65676B', [DARK]: '#65676B' },
  'hero-banner-background': { default: '#FFFFFF', [DARK]: '#FFFFFF' },
  'hosted-view-selected-state': {
    default: 'rgba(45, 136, 255, 0.1)',
    [DARK]: 'rgba(45, 136, 255, 0.1)',
  },
  // 'highlight-bg': { default: '#E7F3FF', [DARK]: '#E7F3FF' },
  'hover-overlay': {
    default: 'rgba(0, 0, 0, 0.05)',
    [DARK]: 'rgba(0, 0, 0, 0.05)',
  },
  'list-cell-chevron': { default: '#65676B', [DARK]: '#65676B' },
  'media-hover': {
    default: 'rgba(68, 73, 80, 0.15)',
    [DARK]: 'rgba(68, 73, 80, 0.15)',
  },
  'media-inner-border': {
    default: 'rgba(0, 0, 0, 0.1)',
    [DARK]: 'rgba(0, 0, 0, 0.1)',
  },
  'media-outer-border': { default: '#FFFFFF', [DARK]: '#FFFFFF' },
  'media-pressed': {
    default: 'rgba(68, 73, 80, 0.35)',
    [DARK]: 'rgba(68, 73, 80, 0.35)',
  },
  'messenger-card-background': { default: '#fafbfc', [DARK]: '#fafbfc' },
  'messenger-reply-background': { default: '#F0F2F5', [DARK]: '#F0F2F5' },
  'overlay-alpha-80': {
    default: 'rgba(244, 244, 244, 0.8)',
    [DARK]: 'rgba(244, 244, 244, 0.8)',
  },
  'overlay-on-media': {
    default: 'rgba(0, 0, 0, 0.6)',
    [DARK]: 'rgba(0, 0, 0, 0.6)',
  },
  'nav-bar-background': { default: '#FFFFFF', [DARK]: '#FFFFFF' },
  'nav-bar-background-gradient': {
    default:
      'linear-gradient(to top, #FFFFFF, rgba(255,255,255.9), rgba(255,255,255,.7), rgba(255,255,255,.4), rgba(255,255,255,0))',
    [DARK]:
      'linear-gradient(to top, #FFFFFF, rgba(255,255,255.9), rgba(255,255,255,.7), rgba(255,255,255,.4), rgba(255,255,255,0))',
  },
  'nav-bar-background-gradient-wash': {
    default:
      'linear-gradient(to top, #F0F2F5, rgba(240,242,245.9), rgba(240,242,245,.7), rgba(240,242,245,.4), rgba(240,242,245,0))',
    [DARK]:
      'linear-gradient(to top, #F0F2F5, rgba(240,242,245.9), rgba(240,242,245,.7), rgba(240,242,245,.4), rgba(240,242,245,0))',
  },
  negative: { default: 'hsl(350, 87%, 55%)', [DARK]: 'hsl(350, 87%, 55%)' },
  'negative-background': {
    default: 'hsl(350, 87%, 55%, 20%)',
    [DARK]: 'hsl(350, 87%, 55%, 20%)',
  },
  'new-notification-background': { default: '#f2f3f5', [DARK]: '#f2f3f5' },
  'non-media-pressed': {
    default: 'rgba(68, 73, 80, 0.15)',
    [DARK]: 'rgba(68, 73, 80, 0.15)',
  },
  'non-media-pressed-on-dark': {
    default: 'rgba(255, 255, 255, 0.3)',
    [DARK]: 'rgba(255, 255, 255, 0.3)',
  },
  // 'notification-badge': { default: '#e41e3f', [DARK]: '#e41e3f' },
  'placeholder-icon': { default: '#65676B', [DARK]: '#65676B' },
  'placeholder-image': {
    default: 'rgb(164, 167, 171)',
    [DARK]: 'rgb(164, 167, 171)',
  },
  // 'placeholder-text': { default: '#65676B', [DARK]: '#65676B' },
  'placeholder-text-on-media': {
    default: 'rgba(255, 255, 255, 0.5)',
    [DARK]: 'rgba(255, 255, 255, 0.5)',
  },
  'popover-background': { default: '#FFFFFF', [DARK]: '#FFFFFF' },
  // positive: { default: '#31A24C', [DARK]: '#31A24C' },
  'positive-background': { default: '#DEEFE1', [DARK]: '#DEEFE1' },
  'press-overlay': {
    default: 'rgba(0, 0, 0, 0.10)',
    [DARK]: 'rgba(0, 0, 0, 0.10)',
  },
  'primary-button-background': { default: '#1B74E4', [DARK]: '#1B74E4' },
  'primary-button-icon': { default: '#FFFFFF', [DARK]: '#FFFFFF' },
  'primary-button-pressed': { default: '#77A7FF', [DARK]: '#77A7FF' },
  'primary-button-text': { default: '#FFFFFF', [DARK]: '#FFFFFF' },
  'primary-deemphasized-button-background': {
    default: '#E7F3FF',
    [DARK]: '#E7F3FF',
  },
  'primary-deemphasized-button-pressed': {
    default: 'rgba(0, 0, 0, 0.05)',
    [DARK]: 'rgba(0, 0, 0, 0.05)',
  },
  'primary-deemphasized-button-pressed-overlay': {
    default: 'rgba(25, 110, 255, 0.15)',
    [DARK]: 'rgba(25, 110, 255, 0.15)',
  },
  'primary-deemphasized-button-text': {
    default: '#1763CF',
    [DARK]: '#1763CF',
  },
  'primary-icon': { default: '#050505', [DARK]: '#050505' },
  'primary-text': { default: '#050505', [DARK]: '#050505' },
  'primary-text-on-media': { default: '#FFFFFF', [DARK]: '#FFFFFF' },
  'primary-web-focus-indicator': { default: '#D24294', [DARK]: '#D24294' },
  'progress-ring-neutral-background': {
    default: 'rgba(0, 0, 0, 0.2)',
    [DARK]: 'rgba(0, 0, 0, 0.2)',
  },
  'progress-ring-neutral-foreground': {
    default: '#000000',
    [DARK]: '#000000',
  },
  'progress-ring-on-media-background': {
    default: 'rgba(255, 255, 255, 0.2)',
    [DARK]: 'rgba(255, 255, 255, 0.2)',
  },
  'progress-ring-on-media-foreground': {
    default: '#FFFFFF',
    [DARK]: '#FFFFFF',
  },
  'progress-ring-blue-background': {
    default: 'rgba(24, 119, 242, 0.2)',
    [DARK]: 'rgba(24, 119, 242, 0.2)',
  },
  'progress-ring-blue-foreground': {
    default: 'hsl(214, 89%, 52%)',
    [DARK]: 'hsl(214, 89%, 52%)',
  },
  'progress-ring-disabled-background': {
    default: 'rgba(190,195,201, 0.2)',
    [DARK]: 'rgba(190,195,201, 0.2)',
  },
  'progress-ring-disabled-foreground': {
    default: '#BEC3C9',
    [DARK]: '#BEC3C9',
  },
  'rating-star-active': { default: '#EB660D', [DARK]: '#EB660D' },
  'scroll-thumb': { default: '#BCC0C4', [DARK]: '#BCC0C4' },
  'scroll-shadow': {
    default: '0 1px 2px rgba(0, 0, 0, 0.1), 0 -1px rgba(0, 0, 0, 0.1) inset',
    [DARK]: '0 1px 2px rgba(0, 0, 0, 0.1), 0 -1px rgba(0, 0, 0, 0.1) inset',
  },
  'secondary-button-background': { default: '#E4E6EB', [DARK]: '#E4E6EB' },
  'secondary-button-background-floating': {
    default: '#ffffff',
    [DARK]: '#ffffff',
  },
  'secondary-button-background-on-dark': {
    default: 'rgba(0, 0, 0, 0.4)',
    [DARK]: 'rgba(0, 0, 0, 0.4)',
  },
  'secondary-button-pressed': {
    default: 'rgba(0, 0, 0, 0.05)',
    [DARK]: 'rgba(0, 0, 0, 0.05)',
  },
  'secondary-button-stroke': {
    default: 'transparent',
    [DARK]: 'transparent',
  },
  'secondary-button-text': { default: '#050505', [DARK]: '#050505' },
  // 'secondary-icon': { default: '#65676B', [DARK]: '#65676B' },
  'secondary-text': { default: '#65676B', [DARK]: '#65676B' },
  'secondary-text-on-media': {
    default: 'rgba(255, 255, 255, 0.9)',
    [DARK]: 'rgba(255, 255, 255, 0.9)',
  },
  'section-header-text': { default: '#4B4C4F', [DARK]: '#4B4C4F' },
  'shadow-1': { default: 'rgba(0, 0, 0, 0.1)', [DARK]: 'rgba(0, 0, 0, 0.1)' },
  'shadow-2': { default: 'rgba(0, 0, 0, 0.2)', [DARK]: 'rgba(0, 0, 0, 0.2)' },
  'shadow-5': { default: 'rgba(0, 0, 0, 0.5)', [DARK]: 'rgba(0, 0, 0, 0.5)' },
  'shadow-8': { default: 'rgba(0, 0, 0, 0.8)', [DARK]: 'rgba(0, 0, 0, 0.8)' },
  'shadow-inset': {
    default: 'rgba(255, 255, 255, 0.5)',
    [DARK]: 'rgba(255, 255, 255, 0.5)',
  },
  'shadow-elevated': {
    default: '0 8px 20px 0 rgba(0, 0, 0, 0.2), 0 2px 4px 0 rgba(0, 0, 0, 0.1)',
    [DARK]: '0 8px 20px 0 rgba(0, 0, 0, 0.2), 0 2px 4px 0 rgba(0, 0, 0, 0.1)',
  },
  'shadow-persistent': {
    default: '0px 0px 12px rgba(52, 72, 84, 0.05)',
    [DARK]: '0px 0px 12px rgba(52, 72, 84, 0.05)',
  },
  'shadow-primary': {
    default: '0px 5px 12px rgba(52, 72, 84, 0.2)',
    [DARK]: '0px 5px 12px rgba(52, 72, 84, 0.2)',
  },
  'surface-background': { default: '#FFFFFF', [DARK]: '#FFFFFF' },
  'switch-active': {
    default: 'hsl(214, 89%, 52%)',
    [DARK]: 'hsl(214, 89%, 52%)',
  },
  'text-highlight': {
    default: 'rgba(24, 119, 242, 0.2)',
    [DARK]: 'rgba(24, 119, 242, 0.2)',
  },
  'input-background': { default: '#FFFFFF', [DARK]: '#FFFFFF' },
  'input-background-disabled': { default: '#F0F2F5', [DARK]: '#F0F2F5' },
  'input-border-color': { default: '#CED0D4', [DARK]: '#CED0D4' },
  'input-border-color-hover': {
    default: color['placeholder-text'], // 'var(--placeholder-text)',
    [DARK]: color['placeholder-text'], // 'var(--placeholder-text)',
  },
  'input-label-color-highlighted': { default: '#1B74E4', [DARK]: '#1B74E4' },
  'text-input-outside-label': { default: '#000000', [DARK]: '#000000' },
  'toast-background': { default: '#FFFFFF', [DARK]: '#FFFFFF' },
  'toast-text': { default: '#1C2B33', [DARK]: '#1C2B33' },
  'toast-text-link': { default: '#216FDB', [DARK]: '#216FDB' },
  'toggle-active-background': { default: '#E7F3FF', [DARK]: '#E7F3FF' },
  'toggle-active-icon': {
    default: 'rgb(24, 119, 242)',
    [DARK]: 'rgb(24, 119, 242)',
  },
  'toggle-active-text': {
    default: 'rgb(24, 119, 242)',
    [DARK]: 'rgb(24, 119, 242)',
  },
  'toggle-button-active-background': {
    default: '#E7F3FF',
    [DARK]: '#E7F3FF',
  },
  'tooltip-background': {
    default: 'rgba(244, 244, 244, 0.8)',
    [DARK]: 'rgba(244, 244, 244, 0.8)',
  },
  'tooltip-box-shadow': {
    default: '0 2px 4px 0 var(--shadow-5)',
    [DARK]: '0 2px 4px 0 var(--shadow-5)',
  },
  wash: { default: '#E4E6EB', [DARK]: '#E4E6EB' },
  'web-wash': { default: '#fafbfc', [DARK]: '#fafbfc' },
  warning: { default: 'hsl(40, 89%, 52%)', [DARK]: 'hsl(40, 89%, 52%)' },
  'chat-bubble-padding-vertical': { default: '8px', [DARK]: '8px' },
  'chat-bubble-padding-horizontal': { default: '12px', [DARK]: '12px' },
  'chat-bubble-border-radius': { default: '18px', [DARK]: '18px' },
  'chat-text-blockquote-color-background-line': {
    default: 'rgba(0, 0, 0, 0.12)',
    [DARK]: 'rgba(0, 0, 0, 0.12)',
  },
  'chat-text-blockquote-color-text-primary-media': {
    default: 'rgba(255, 255, 255, 0.7)',
    [DARK]: 'rgba(255, 255, 255, 0.7)',
  },
  'chat-incoming-message-bubble-background-color': {
    default: '#F0F0F0',
    [DARK]: '#F0F0F0',
  },
  'chat-replied-message-background-color': {
    default: 'rgba(0, 0, 0, 0.03)',
    [DARK]: 'rgba(0, 0, 0, 0.03)',
  },
  'radio-border-color': {
    default: 'var(--primary-icon)',
    [DARK]: 'var(--primary-icon)',
  },
  'radio-border-color-disabled': {
    default: 'var(--disabled-button-background)',
    [DARK]: 'var(--disabled-button-background)',
  },
  'radio-border-color-selected': {
    default: 'var(--accent)',
    [DARK]: 'var(--accent)',
  },
  'radio-checked-icon-color': {
    default: 'var(--accent)',
    [DARK]: 'var(--accent)',
  },
  'radio-checked-icon-color-disabled': {
    default: 'var(--disabled-button-background)',
    [DARK]: 'var(--disabled-button-background)',
  },
  'fb-logo-color': { default: '#2D88FF', [DARK]: '#2D88FF' },
  'dialog-anchor-vertical-padding': { default: '0px', [DARK]: '0px' },
  'header-height': { default: '0px', [DARK]: '0px' },
  'global-panel-width': { default: '0px', [DARK]: '0px' },
  'global-panel-width-expanded': { default: '0px', [DARK]: '0px' },
  'alert-banner-corner-radius': { default: '8px', [DARK]: '8px' },
  'button-corner-radius': { default: '6px', [DARK]: '6px' },
  'button-corner-radius-medium': { default: '10px', [DARK]: '10px' },
  'button-corner-radius-large': { default: '12px', [DARK]: '12px' },
  'button-height-large': { default: '40px', [DARK]: '40px' },
  'button-height-medium': { default: '36px', [DARK]: '36px' },
  'button-padding-horizontal-large': { default: '16px', [DARK]: '16px' },
  'button-padding-horizontal-medium': { default: '16px', [DARK]: '16px' },
  'button-icon-padding-large': { default: '16px', [DARK]: '16px' },
  'button-icon-padding-medium': { default: '16px', [DARK]: '16px' },
  'button-inner-icon-spacing-large': { default: '3px', [DARK]: '3px' },
  'button-inner-icon-spacing-medium': { default: '3px', [DARK]: '3px' },
  'blueprint-button-height-medium': { default: '40px', [DARK]: '40px' },
  'blueprint-button-height-large': { default: '48px', [DARK]: '48px' },
  'card-corner-radius': { default: '8px', [DARK]: '8px' },
  'card-box-shadow': {
    default: '0 12px 28px 0 var(--shadow-2), 0 2px 4px 0 var(--shadow-1)',
    [DARK]: '0 12px 28px 0 var(--shadow-2), 0 2px 4px 0 var(--shadow-1)',
  },
  'card-padding-horizontal': { default: '10px', [DARK]: '10px' },
  'card-padding-vertical': { default: '20px', [DARK]: '20px' },
  'chip-corner-radius': { default: '6px', [DARK]: '6px' },
  'dialog-corner-radius': { default: '8px', [DARK]: '8px' },
  'glimmer-corner-radius': { default: '8px', [DARK]: '8px' },
  'image-corner-radius': { default: '4px', [DARK]: '4px' },
  'input-corner-radius': { default: '6px', [DARK]: '6px' },
  'input-border-width': { default: '1px', [DARK]: '1px' },
  'nav-list-cell-corner-radius': { default: '8px', [DARK]: '8px' },
  'list-cell-corner-radius': { default: '8px', [DARK]: '8px' },
  'list-cell-min-height': { default: '52px', [DARK]: '52px' },
  'list-cell-padding-vertical': { default: '20px', [DARK]: '20px' },
  'list-cell-padding-vertical-with-addon': {
    default: '14px',
    [DARK]: '14px',
  },
  'menu-item-base-margin-horizontal': { default: '8px', [DARK]: '8px' },
  'menu-item-base-padding-horizontal': { default: '8px', [DARK]: '8px' },
  'nav-list-cell-min-height': { default: '0px', [DARK]: '0px' },
  'nav-list-cell-padding-vertical': { default: '16px', [DARK]: '16px' },
  'nav-list-cell-padding-vertical-with-addon': {
    default: '16px',
    [DARK]: '16px',
  },
  'page-footer-padding-vertical': { default: '16px', [DARK]: '16px' },
  'section-header-addOnEnd-margin-horizontal': {
    default: '8px',
    [DARK]: '8px',
  },
  'section-header-addOnStart-margin-horizontal': {
    default: '12px',
    [DARK]: '12px',
  },
  'section-header-addOnEnd-button-padding-horizontal': {
    default: '0px',
    [DARK]: '0px',
  },
  'section-header-addOnEnd-button-padding-vertical': {
    default: '0px',
    [DARK]: '0px',
  },
  'section-header-padding-vertical': { default: '16px', [DARK]: '16px' },
  'section-header-subtitle-margin-vertical': {
    default: '14px',
    [DARK]: '14px',
  },
  'section-header-subtitle-with-addOnEnd-margin-vertical': {
    default: '6px',
    [DARK]: '6px',
  },
  'text-badge-corner-radius': { default: '4px', [DARK]: '4px' },
  'text-badge-padding-horizontal': { default: '6px', [DARK]: '6px' },
  'text-badge-padding-vertical': { default: '6px', [DARK]: '6px' },
  'text-input-multi-padding-between-text-scrollbar': {
    default: '20px',
    [DARK]: '20px',
  },
  'text-input-multi-padding-scrollbar': { default: '16px', [DARK]: '16px' },
  'text-input-caption-margin-top': { default: '10px', [DARK]: '10px' },
  'text-input-label-top': { default: '22px', [DARK]: '22px' },
  'text-input-min-height': { default: '64px', [DARK]: '64px' },
  'text-input-padding-vertical': { default: '12px', [DARK]: '12px' },
  'toast-addon-padding-horizontal': { default: '6px', [DARK]: '6px' },
  'toast-addon-padding-vertical': { default: '6px', [DARK]: '6px' },
  'toast-container-max-width': { default: '100%', [DARK]: '100%' },
  'toast-container-min-width': { default: '288px', [DARK]: '288px' },
  'toast-container-padding-horizontal': { default: '10px', [DARK]: '10px' },
  'toast-container-padding-vertical': { default: '16px', [DARK]: '16px' },
  'toast-corner-radius': { default: '8px', [DARK]: '8px' },
  'tooltip-corner-radius': { default: '8px', [DARK]: '8px' },
  'typeahead-list-outer-padding-vertical': { default: '2px', [DARK]: '2px' },
  'fds-animation-enter-exit-in': {
    default: 'cubic-bezier(0.14, 1, 0.34, 1)',
    [DARK]: 'cubic-bezier(0.14, 1, 0.34, 1)',
  },
  'fds-animation-enter-exit-out': {
    default: 'cubic-bezier(0.45, 0.1, 0.2, 1)',
    [DARK]: 'cubic-bezier(0.45, 0.1, 0.2, 1)',
  },
  'fds-animation-swap-shuffle-in': {
    default: 'cubic-bezier(0.14, 1, 0.34, 1)',
    [DARK]: 'cubic-bezier(0.14, 1, 0.34, 1)',
  },
  'fds-animation-swap-shuffle-out': {
    default: 'cubic-bezier(0.45, 0.1, 0.2, 1)',
    [DARK]: 'cubic-bezier(0.45, 0.1, 0.2, 1)',
  },
  'fds-animation-move-in': {
    default: 'cubic-bezier(0.17, 0.17, 0, 1)',
    [DARK]: 'cubic-bezier(0.17, 0.17, 0, 1)',
  },
  'fds-animation-move-out': {
    default: 'cubic-bezier(0.17, 0.17, 0, 1)',
    [DARK]: 'cubic-bezier(0.17, 0.17, 0, 1)',
  },
  'fds-animation-expand-collapse-in': {
    default: 'cubic-bezier(0.17, 0.17, 0, 1)',
    [DARK]: 'cubic-bezier(0.17, 0.17, 0, 1)',
  },
  'fds-animation-expand-collapse-out': {
    default: 'cubic-bezier(0.17, 0.17, 0, 1)',
    [DARK]: 'cubic-bezier(0.17, 0.17, 0, 1)',
  },
  'fds-animation-passive-move-in': {
    default: 'cubic-bezier(0.5, 0, 0.1, 1)',
    [DARK]: 'cubic-bezier(0.5, 0, 0.1, 1)',
  },
  'fds-animation-passive-move-out': {
    default: 'cubic-bezier(0.5, 0, 0.1, 1)',
    [DARK]: 'cubic-bezier(0.5, 0, 0.1, 1)',
  },
  'fds-animation-quick-move-in': {
    default: 'cubic-bezier(0.1, 0.9, 0.2, 1)',
    [DARK]: 'cubic-bezier(0.1, 0.9, 0.2, 1)',
  },
  'fds-animation-quick-move-out': {
    default: 'cubic-bezier(0.1, 0.9, 0.2, 1)',
    [DARK]: 'cubic-bezier(0.1, 0.9, 0.2, 1)',
  },
  'fds-animation-fade-in': {
    default: 'cubic-bezier(0, 0, 1, 1)',
    [DARK]: 'cubic-bezier(0, 0, 1, 1)',
  },
  'fds-animation-fade-out': {
    default: 'cubic-bezier(0, 0, 1, 1)',
    [DARK]: 'cubic-bezier(0, 0, 1, 1)',
  },
  'fds-duration-extra-extra-short-in': { default: '100ms', [DARK]: '100ms' },
  'fds-duration-extra-extra-short-out': { default: '100ms', [DARK]: '100ms' },
  'fds-duration-extra-short-in': { default: '200ms', [DARK]: '200ms' },
  'fds-duration-extra-short-out': { default: '150ms', [DARK]: '150ms' },
  'fds-duration-short-in': { default: '280ms', [DARK]: '280ms' },
  'fds-duration-short-out': { default: '200ms', [DARK]: '200ms' },
  'fds-duration-medium-in': { default: '400ms', [DARK]: '400ms' },
  'fds-duration-medium-out': { default: '350ms', [DARK]: '350ms' },
  'fds-duration-long-in': { default: '500ms', [DARK]: '500ms' },
  'fds-duration-long-out': { default: '350ms', [DARK]: '350ms' },
  'fds-duration-extra-long-in': { default: '1000ms', [DARK]: '1000ms' },
  'fds-duration-extra-long-out': { default: '1000ms', [DARK]: '1000ms' },
  'fds-duration-none': { default: '0ms', [DARK]: '0ms' },
  'fds-fast': { default: '200ms', [DARK]: '200ms' },
  'fds-slow': { default: '400ms', [DARK]: '400ms' },
  'font-family-apple': {
    default:
      "system-ui, -apple-system, BlinkMacSystemFont, '.SFNSText-Regular', sans-serif",
    [DARK]:
      "system-ui, -apple-system, BlinkMacSystemFont, '.SFNSText-Regular', sans-serif",
  },
  'font-family-code': {
    default: 'ui-monospace, Menlo, Consolas, Monaco, monospace',
    [DARK]: 'ui-monospace, Menlo, Consolas, Monaco, monospace',
  },
  'font-family-default': {
    default: 'Helvetica, Arial, sans-serif',
    [DARK]: 'Helvetica, Arial, sans-serif',
  },
  'font-family-segoe': {
    default: 'Segoe UI Historic, Segoe UI, Helvetica, Arial, sans-serif',
    [DARK]: 'Segoe UI Historic, Segoe UI, Helvetica, Arial, sans-serif',
  },
  'body-font-family': {
    default: 'Placeholder Font',
    [DARK]: 'Placeholder Font',
  },
  'body-font-size': { default: '0.9375rem', [DARK]: '0.9375rem' },
  'body-font-weight': { default: '400', [DARK]: '400' },
  'body-line-height': { default: '1.3333', [DARK]: '1.3333' },
  'body-emphasized-font-family': {
    default: 'Placeholder Font',
    [DARK]: 'Placeholder Font',
  },
  'body-emphasized-font-size': { default: '0.9375rem', [DARK]: '0.9375rem' },
  'body-emphasized-font-weight': { default: '600', [DARK]: '600' },
  'body-emphasized-line-height': { default: '1.3333', [DARK]: '1.3333' },
  'headline1-font-family': {
    default: 'Optimistic Display Bold, system-ui, sans-serif',
    [DARK]: 'Optimistic Display Bold, system-ui, sans-serif',
  },
  'headline1-font-size': { default: '1.75rem', [DARK]: '1.75rem' },
  'headline1-font-weight': { default: '700', [DARK]: '700' },
  'headline1-line-height': { default: '1.2143', [DARK]: '1.2143' },
  'headline2-font-family': {
    default: 'Optimistic Display Bold, system-ui, sans-serif',
    [DARK]: 'Optimistic Display Bold, system-ui, sans-serif',
  },
  'headline2-font-size': { default: '1.5rem', [DARK]: '1.5rem' },
  'headline2-font-weight': { default: '700', [DARK]: '700' },
  'headline2-line-height': { default: '1.25', [DARK]: '1.25' },
  'headline3-font-family': {
    default: 'Optimistic Display Bold, system-ui, sans-serif',
    [DARK]: 'Optimistic Display Bold, system-ui, sans-serif',
  },
  'headline3-font-size': { default: '1.0625rem', [DARK]: '1.0625rem' },
  'headline3-font-weight': { default: '700', [DARK]: '700' },
  'headline3-line-height': { default: '1.2941', [DARK]: '1.2941' },
  'meta-font-family': {
    default: 'Placeholder Font',
    [DARK]: 'Placeholder Font',
  },
  'meta-font-size': { default: '0.8125rem', [DARK]: '0.8125rem' },
  'meta-font-weight': { default: '400', [DARK]: '400' },
  'meta-line-height': { default: '1.3846', [DARK]: '1.3846' },
  'meta-emphasized-font-family': {
    default: 'Placeholder Font',
    [DARK]: 'Placeholder Font',
  },
  'meta-emphasized-font-size': { default: '0.8125rem', [DARK]: '0.8125rem' },
  'meta-emphasized-font-weight': { default: '600', [DARK]: '600' },
  'meta-emphasized-line-height': { default: '1.3846', [DARK]: '1.3846' },
  'primary-label-font-family': {
    default: 'Optimistic Display Medium, system-ui, sans-serif',
    [DARK]: 'Optimistic Display Medium, system-ui, sans-serif',
  },
  'primary-label-font-size': { default: '1.0625rem', [DARK]: '1.0625rem' },
  'primary-label-font-weight': { default: '500', [DARK]: '500' },
  'primary-label-line-height': { default: '1.2941', [DARK]: '1.2941' },
  'secondary-label-font-family': {
    default: 'Placeholder Font',
    [DARK]: 'Placeholder Font',
  },
  'secondary-label-font-size': { default: '0.9375rem', [DARK]: '0.9375rem' },
  'secondary-label-font-weight': { default: '500', [DARK]: '500' },
  'secondary-label-line-height': { default: '1.3333', [DARK]: '1.3333' },
  'tertiary-label-font-family': {
    default: 'Placeholder Font',
    [DARK]: 'Placeholder Font',
  },
  'tertiary-label-font-size': { default: '0.6875rem', [DARK]: '0.6875rem' },
  'tertiary-label-font-weight': { default: '500', [DARK]: '500' },
  'tertiary-label-line-height': { default: '1.4545', [DARK]: '1.4545' },
  'text-input-field-font-family': {
    default: 'Placeholder Font',
    [DARK]: 'Placeholder Font',
  },
  'text-input-field-font-size': { default: '1rem', [DARK]: '1rem' },
  'text-input-field-font-weight': { default: '500', [DARK]: '500' },
  'text-input-field-line-height': { default: '1.2941', [DARK]: '1.2941' },
  'text-input-label-font-family': {
    default: 'Placeholder Font',
    [DARK]: 'Placeholder Font',
  },
  'text-input-label-font-size': { default: '17px', [DARK]: '17px' },
  'text-input-label-font-size-scale-multiplier': {
    default: '0.75',
    [DARK]: '0.75',
  },
  'text-input-label-font-weight': { default: '400', [DARK]: '400' },
  'text-input-label-line-height': { default: '1.2941', [DARK]: '1.2941' },
  'dialog-size-medium-max-width': { default: '700px', [DARK]: '700px' },
  'dialog-size-medium-width': { default: '100%', [DARK]: '100%' },
  'dialog-size-small-max-width': { default: '548px', [DARK]: '548px' },
  'dialog-size-small-width': { default: '100%', [DARK]: '100%' },
  'focus-ring-outline-forced-colors': {
    default: '2px auto transparent !important',
    [DARK]: '2px auto transparent !important',
  },
  'focus-ring-outline-link': {
    default: '2px auto var(--focus-ring-blue)',
    [DARK]: '2px auto var(--focus-ring-blue)',
  },
  'focus-ring-shadow-default': {
    default: '0 0 0 2px var(--always-white), 0 0 0 4px var(--focus-ring-blue)',
    [DARK]: '0 0 0 2px var(--always-white), 0 0 0 4px var(--focus-ring-blue)',
  },
  'focus-ring-shadow-inset': {
    default:
      '0 0 0 2px var(--focus-ring-blue) inset, 0 0 0 4px var(--always-white) inset',
    [DARK]:
      '0 0 0 2px var(--focus-ring-blue) inset, 0 0 0 4px var(--always-white) inset',
  },
  'glimmer-animation-direction': {
    default: 'alternate',
    [DARK]: 'alternate',
  },
  'glimmer-animation-duration': { default: '1000ms', [DARK]: '1000ms' },
  'glimmer-animation-timing-function': {
    default: 'steps(10, end)',
    [DARK]: 'steps(10, end)',
  },
  'glimmer-opacity-min': { default: '0.25', [DARK]: '0.25' },
  'glimmer-opacity-max': { default: '1', [DARK]: '1' },
  'radio-checked-icon-size-large': { default: '12px', [DARK]: '12px' },
  'radio-checked-icon-size-medium': { default: '12px', [DARK]: '12px' },
  'radio-border-width': { default: '2px', [DARK]: '2px' },
  'radio-size-large': { default: '24px', [DARK]: '24px' },
  'radio-size-medium': { default: '20px', [DARK]: '20px' },
  'dataviz-primary-2': {
    default: 'rgb(134,218,255)',
    [DARK]: 'rgb(134,218,255)',
  },
  'dataviz-primary-3': {
    default: 'rgb(95,170,255)',
    [DARK]: 'rgb(95,170,255)',
  },
  'dataviz-secondary-1': {
    default: 'rgb(118,62,230)',
    [DARK]: 'rgb(118,62,230)',
  },
  'dataviz-secondary-2': {
    default: 'rgb(147,96,247)',
    [DARK]: 'rgb(147,96,247)',
  },
  'dataviz-secondary-3': {
    default: 'rgb(219,26,139)',
    [DARK]: 'rgb(219,26,139)',
  },
  'dataviz-supplementary-1': {
    default: 'rgb(255,122,105)',
    [DARK]: 'rgb(255,122,105)',
  },
  'dataviz-supplementary-2': {
    default: 'rgb(241,168,23)',
    [DARK]: 'rgb(241,168,23)',
  },
  'dataviz-supplementary-3': {
    default: 'rgb(49,162,76)',
    [DARK]: 'rgb(49,162,76)',
  },
  'dataviz-supplementary-4': {
    default: 'rgb(50,52,54)',
    [DARK]: 'rgb(50,52,54)',
  },
  'wig-oyster': { default: '#ece9e7', [DARK]: '#ece9e7' },
  'wig-oyster-white-25': { default: '#f0eeec', [DARK]: '#f0eeec' },
  'wig-oyster-white-40': { default: '#f3f1f0', [DARK]: '#f3f1f0' },
  'wig-oyster-white-50': { default: '#f7f6f5', [DARK]: '#f7f6f5' },
  'wig-oyster-white-60': { default: '#f2f1f0', [DARK]: '#f2f1f0' },
  'wig-oyster-black-05': { default: '#dfdddb', [DARK]: '#dfdddb' },
  'wig-oyster-black-10': { default: '#d3d1cf', [DARK]: '#d3d1cf' },
  'wig-oyster-black-20': { default: '#bcbab8', [DARK]: '#bcbab8' },
  'wig-oyster-black-40': { default: '#8d8b8a', [DARK]: '#8d8b8a' },
  'wig-oyster-black-50': { default: '#757473', [DARK]: '#757473' },
  'wig-oyster-black-60': { default: '#555453', [DARK]: '#555453' },
  'wig-oyster-black-70': { default: '#474645', [DARK]: '#474645' },
  'wig-oyster-black-85': { default: '#232222', [DARK]: '#232222' },
  'wig-desktop-wash': { default: '#ebe9e7', [DARK]: '#ebe9e7' },
  'wig-light-grey': { default: '#ebedf0', [DARK]: '#ebedf0' },
  'wig-grey': { default: '#373e4c', [DARK]: '#373e4c' },
  'wig-white': { default: '#ffffff', [DARK]: '#ffffff' },
  'wig-blue': { default: '#1763CF', [DARK]: '#1763CF' },
  'wig-blue-button': { default: '#1B74E4', [DARK]: '#1B74E4' },
  'wig-blue-black-20': { default: '#1060c8', [DARK]: '#1060c8' },
  'wig-blue-black-40': { default: '#0d54af', [DARK]: '#0d54af' },
  'wig-blue-white-70': { default: '#b8d7fd', [DARK]: '#b8d7fd' },
  'wig-blue-white-90': { default: '#e7f1fe', [DARK]: '#e7f1fe' },
  'wig-red': { default: '#fa3e3e', [DARK]: '#fa3e3e' },
  'wig-green': { default: '#42b72a', [DARK]: '#42b72a' },
  'wig-purple': { default: '#9678d2', [DARK]: '#9678d2' },
  'wig-coral': { default: '#ff645a', [DARK]: '#ff645a' },
  'wig-orange': { default: '#ff8216', [DARK]: '#ff8216' },
  'wig-yellow': { default: '#f0c850', [DARK]: '#f0c850' },
  'wig-aqua': { default: '#64d2d2', [DARK]: '#64d2d2' },
  'wig-pink': { default: '#ffb4c8', [DARK]: '#ffb4c8' },
  'wig-cherry': { default: '#e62546', [DARK]: '#e62546' },
  'wig-blush': { default: '#f0c8a0', [DARK]: '#f0c8a0' },
  'wig-khaki': { default: '#c4c078', [DARK]: '#c4c078' },
  'wig-teal': { default: '#00c882', [DARK]: '#00c882' },
  'wig-sky': { default: '#50b4f0', [DARK]: '#50b4f0' },
  'wig-grass': { default: '#77b526', [DARK]: '#77b526' },
  'wig-black-alpha-05': {
    default: 'rgba(0, 0, 0, 0.05)',
    [DARK]: 'rgba(0, 0, 0, 0.05)',
  },
  'wig-black-alpha-10': {
    default: 'rgba(0, 0, 0, 0.1)',
    [DARK]: 'rgba(0, 0, 0, 0.1)',
  },
  'wig-page-background': { default: '#fafbfc', [DARK]: '#fafbfc' },
  'wig-input-background': { default: '#f2f3f5', [DARK]: '#f2f3f5' },
  'wig-selected-background': {
    default: 'rgba(0, 0, 0, 0.1)',
    [DARK]: 'rgba(0, 0, 0, 0.1)',
  },
  'wig-hovered-background': {
    default: 'rgba(0, 0, 0, 0.05)',
    [DARK]: 'rgba(0, 0, 0, 0.05)',
  },
  'wig-official-entity': { default: '#00c882', [DARK]: '#00c882' },
  'wig-iris-100': { default: '#4326C4', [DARK]: '#4326C4' },
  'wig-mushroom-120': { default: '#896674', [DARK]: '#896674' },
  'wig-divider': { default: '#E1E1E2', [DARK]: '#E1E1E2' },
  'fds-www-wash': { default: '#EBEDF0', [DARK]: '#EBEDF0' },
  'wig-nav-background': { default: '#fafbfc', [DARK]: '#fafbfc' },
  'wig-nav-channel-gradient': {
    default: 'linear-gradient(90deg, rgba(0,0,0,0.0), rgba(0,0,0,0.02))',
    [DARK]: 'linear-gradient(90deg, rgba(0,0,0,0.0), rgba(0,0,0,0.02))',
  },
  'wig-chat-background': { default: '#FFFFFF', [DARK]: '#FFFFFF' },
  'wig-contrast-background': { default: '#FFFFFF', [DARK]: '#FFFFFF' },
  'wig-chat-bubble-sender': { default: '#f2f3f5', [DARK]: '#f2f3f5' },
  'wig-chat-bubble': { default: '#373e4c', [DARK]: '#373e4c' },
  'wig-foreign-entity': { default: '#B11710', [DARK]: '#B11710' },
  'wig-chat-default-color': { default: '#373e4c', [DARK]: '#373e4c' },
  'wig-channel-icon-default-background': {
    default: '#373e4c',
    [DARK]: '#373e4c',
  },
  'wig-group-cover-default-background': {
    default: '#373e4c',
    [DARK]: '#373e4c',
  },
  'wig-quick-chat-settings-shadow-start': {
    default: 'rgba(0, 0, 0, 0.1)',
    [DARK]: 'rgba(0, 0, 0, 0.1)',
  },
  'wig-quick-chat-settings-shadow-end': {
    default: 'rgba(0, 0, 0, 0.3)',
    [DARK]: 'rgba(0, 0, 0, 0.3)',
  },
  'wig-primary-iris-90': { default: '#573bd3', [DARK]: '#573bd3' },
  'workplace-chart-background': { default: '#ECF3FF', [DARK]: '#ECF3FF' },
  'workplace-chart-foreground': { default: '#C2DCFC', [DARK]: '#C2DCFC' },
  'workplace-chart-caption': { default: '#FFFFFF', [DARK]: '#FFFFFF' },
  'tasks-priority-unbreak': { default: '#8036cc', [DARK]: '#8036cc' },
  'tasks-priority-high': { default: '#f23232', [DARK]: '#f23232' },
  'tasks-priority-mid': { default: '#f88639', [DARK]: '#f88639' },
  'tasks-priority-low': { default: '#eec954', [DARK]: '#eec954' },
  'tasks-priority-wish': { default: '#5cc9b4', [DARK]: '#5cc9b4' },
  'tasks-priority-none': { default: '#c4d2e7', [DARK]: '#c4d2e7' },
});
