/**
 * @fileoverview
 * Copyright (c) Xuan Tien and affiliated entities.
 * All rights reserved. This source code is licensed under the MIT license.
 * See the LICENSE file in the root directory for details.
 */

export const CLDRDateFormatConfig = {
  supportedPHPFormatsKeys: {
    D: "E",
    "D g:ia": "Ejm",
    "D M d": "MMMEd",
    "D M d, Y": "yMMMEd",
    "D M j": "MMMEd",
    "D M j, y": "yMMMEd",
    "D, M j": "MMMEd",
    "D, M j, Y": "yMMMEd",
    "F d": "MMMMd",
    "F d, Y": "date_long",
    "F j": "MMMMd",
    "F j, Y": "date_long",
    "F j, Y @ g:i A": "dateTime_long_short",
    "F j, Y g:i a": "dateTime_long_short",
    "F j, Y @ g:i:s A": "dateTime_long_medium",
    "F jS": "MMMMd",
    "F jS, g:ia": "dateTime_long_short",
    "F jS, Y": "date_long",
    "F Y": "yMMMM",
    "g A": "j",
    "G:i": "time_short",
    "g:i": "time_short",
    "g:i a": "time_short",
    "g:i A": "time_short",
    "g:i:s A": "time_medium",
    "g:ia": "time_short",
    "g:iA": "time_short",
    "g:ia F jS, Y": "dateTime_long_short",
    "g:iA l, F jS": "dateTime_full_short",
    "g:ia M jS": "dateTime_medium_short",
    "g:ia, F jS": "dateTime_long_short",
    "g:iA, l M jS": "dateTime_full_short",
    "h:i a": "time_short",
    "h:m:s m/d/Y": "dateTime_short_short",
    j: "d",
    "j F Y": "date_long",
    "l F d, Y": "date_full",
    "l, F d, Y": "date_full",
    "l, F j": "date_full",
    "l, F j, Y": "date_full",
    "l, F jS": "date_full",
    "l, F jS, g:ia": "dateTime_full_short",
    "l, M j": "date_full",
    "l, M j, Y": "date_full",
    "l, M j, Y g:ia": "dateTime_full_short",
    "M d": "MMMd",
    "M d, Y": "date_medium",
    "M d, Y g:ia": "dateTime_medium_short",
    "M d, Y ga": "dateTime_medium_short",
    "M j": "MMMd",
    "M j, Y": "date_medium",
    "M j, Y g:i A": "dateTime_medium_short",
    "M j, Y g:ia": "dateTime_medium_short",
    "M jS, g:ia": "dateTime_medium_short",
    "M y": "yMMM",
    "M Y": "yMMM",
    "M. d": "MMMd",
    "M. d, Y": "date_medium",
    "m/d": "Md",
    "m/d/Y g:ia": "dateTime_short_short",
    "m/d/y H:i:s": "dateTime_short_short",
    n: "M",
    "n/j": "Md",
    "n/j, g:ia": "dateTime_short_short",
    "n/j/y": "date_short",
    Y: "y",
  },
  isLocaleInConfigerator: true,
  CLDRConfigeratorFormats: {
    dateFormats: {
      full: "EEEE, MMMM d, y",
      long: "MMMM d, y",
      medium: "MMM d, y",
      short: "M/d/yy",
    },
    timeFormats: {
      full: "h:mm:ss a zzzz",
      long: "h:mm:ss a z",
      medium: "h:mm:ss a",
      short: "h:mm a",
    },
    dateTimeFormats: {
      full: "{1} 'at' {0}",
      long: "{1} 'at' {0}",
      medium: "{1}, {0}",
      short: "{1}, {0}",
    },
    availableFormats: {
      Bh: "h B",
      Bhm: "h:mm B",
      Bhms: "h:mm:ss B",
      E: "ccc",
      EBhm: "E h:mm B",
      EBhms: "E h:mm:ss B",
      EHm: "E HH:mm",
      EHms: "E HH:mm:ss",
      Ed: "d E",
      Ehm: "E h:mm a",
      Ehms: "E h:mm:ss a",
      Gy: "y G",
      GyMMM: "MMM y G",
      GyMMMEd: "E, MMM d, y G",
      GyMMMd: "MMM d, y G",
      H: "HH",
      Hm: "HH:mm",
      Hms: "HH:mm:ss",
      Hmsv: "HH:mm:ss v",
      Hmv: "HH:mm v",
      M: "L",
      MEd: "E, M/d",
      MMM: "LLL",
      MMMEd: "E, MMM d",
      "MMMMW-count-one": "'week' W 'of' MMMM",
      "MMMMW-count-other": "'week' W 'of' MMMM",
      MMMMd: "MMMM d",
      MMMd: "MMM d",
      Md: "M/d",
      d: "d",
      h: "h a",
      hm: "h:mm a",
      hms: "h:mm:ss a",
      hmsv: "h:mm:ss a v",
      hmv: "h:mm a v",
      ms: "mm:ss",
      y: "y",
      yM: "M/y",
      yMEd: "E, M/d/y",
      yMMM: "MMM y",
      yMMMEd: "E, MMM d, y",
      yMMMM: "MMMM y",
      yMMMd: "MMM d, y",
      yMd: "M/d/y",
      yQQQ: "QQQ y",
      yQQQQ: "QQQQ y",
      "yw-count-one": "'week' w 'of' Y",
      "yw-count-other": "'week' w 'of' Y",
    },
  },
  CLDRRegionalConfigeratorFormats: {
    dateFormats: {
      full: "EEEE, MMMM d, y",
      long: "MMMM d, y",
      medium: "MMM d, y",
      short: "M/d/yy",
    },
    timeFormats: {
      full: "h:mm:ss a zzzz",
      long: "h:mm:ss a z",
      medium: "h:mm:ss a",
      short: "h:mm a",
    },
    dateTimeFormats: {
      full: "{1} 'at' {0}",
      long: "{1} 'at' {0}",
      medium: "{1}, {0}",
      short: "{1}, {0}",
    },
    availableFormats: {
      Bh: "h B",
      Bhm: "h:mm B",
      Bhms: "h:mm:ss B",
      E: "ccc",
      EBhm: "E h:mm B",
      EBhms: "E h:mm:ss B",
      EHm: "E HH:mm",
      EHms: "E HH:mm:ss",
      Ed: "d E",
      Ehm: "E h:mm a",
      Ehms: "E h:mm:ss a",
      Gy: "y G",
      GyMMM: "MMM y G",
      GyMMMEd: "E, MMM d, y G",
      GyMMMd: "MMM d, y G",
      H: "HH",
      Hm: "HH:mm",
      Hms: "HH:mm:ss",
      Hmsv: "HH:mm:ss v",
      Hmv: "HH:mm v",
      M: "L",
      MEd: "E, M/d",
      MMM: "LLL",
      MMMEd: "E, MMM d",
      "MMMMW-count-one": "'week' W 'of' MMMM",
      "MMMMW-count-other": "'week' W 'of' MMMM",
      MMMMd: "MMMM d",
      MMMd: "MMM d",
      Md: "M/d",
      d: "d",
      h: "h a",
      hm: "h:mm a",
      hms: "h:mm:ss a",
      hmsv: "h:mm:ss a v",
      hmv: "h:mm a v",
      ms: "mm:ss",
      y: "y",
      yM: "M/y",
      yMEd: "E, M/d/y",
      yMMM: "MMM y",
      yMMMEd: "E, MMM d, y",
      yMMMM: "MMMM y",
      yMMMd: "MMM d, y",
      yMd: "M/d/y",
      yQQQ: "QQQ y",
      yQQQQ: "QQQQ y",
      "yw-count-one": "'week' w 'of' Y",
      "yw-count-other": "'week' w 'of' Y",
    },
  },
  CLDRToPHPSymbolConversion: {
    G: "",
    yyyy: "Y",
    yy: "y",
    y: "Y",
    LLLLL: "M",
    LLLL: "f",
    LLL: "M",
    LL: "m",
    L: "n",
    MMMMM: "M",
    MMMM: "F",
    MMM: "M",
    MM: "m",
    M: "n",
    dd: "d",
    d: "j",
    ccccc: "D",
    cccc: "l",
    ccc: "D",
    cc: "D",
    c: "D",
    EEEEE: "D",
    EEEE: "l",
    EEE: "D",
    EE: "D",
    E: "D",
    aaaaa: "A",
    aaaa: "A",
    aaa: "A",
    aa: "A",
    a: "A",
    bbbbb: "A",
    bbbb: "A",
    bbb: "A",
    bb: "A",
    b: "A",
    BBBBB: "A",
    BBBB: "A",
    BBB: "A",
    BB: "A",
    B: "A",
    HH: "H",
    H: "G",
    hh: "h",
    h: "g",
    K: "g",
    mm: "i",
    m: "i",
    ss: "s",
    s: "s",
    z: "",
    zz: "",
    zzz: "",
  },
  intlDateSpecialChars: {
    cldrDelimiter: "'",
    singleQuote: "'",
    singleQuoteHolder: "*",
  },
};
