/**
 * @fileoverview
 * Copyright (c) Xuan Tien and affiliated entities.
 * All rights reserved. This source code is licensed under the MIT license.
 * See the LICENSE file in the root directory for details.
 */
// const fs = require('fs');

// const darkTheme = {
//   'fds-black': '#000000',
//   'fds-black-alpha-05': 'rgba(0, 0, 0, 0.05)',
//   'fds-black-alpha-10': 'rgba(0, 0, 0, 0.1)',
//   'fds-black-alpha-15': 'rgba(0, 0, 0, 0.15)',
//   'fds-black-alpha-20': 'rgba(0, 0, 0, 0.2)',
//   'fds-black-alpha-30': 'rgba(0, 0, 0, 0.3)',
//   'fds-black-alpha-40': 'rgba(0, 0, 0, 0.4)',
//   'fds-black-alpha-50': 'rgba(0, 0, 0, 0.5)',
//   'fds-black-alpha-60': 'rgba(0, 0, 0, 0.6)',
//   'fds-black-alpha-80': 'rgba(0, 0, 0, 0.8)',
//   'fds-blue-05': '#ECF3FF',
//   'fds-blue-30': '#AAC9FF',
//   'fds-blue-40': '#77A7FF',
//   'fds-blue-60': '#1877F2',
//   'fds-blue-70': '#2851A3',
//   'fds-blue-80': '#1D3C78',
//   'fds-button-text': '#444950',
//   'fds-comment-background': '#F2F3F5',
//   'fds-dark-mode-gray-100': '#1C1C1C',
//   'fds-dark-mode-gray-35': '#CCCCCC',
//   'fds-dark-mode-gray-50': '#828282',
//   'fds-dark-mode-gray-70': '#4A4A4A',
//   'fds-dark-mode-gray-80': '#373737',
//   'fds-dark-mode-gray-90': '#282828',
//   'fds-gray-00': '#F5F6F7',
//   'fds-gray-05': '#F2F3F5',
//   'fds-gray-10': '#EBEDF0',
//   'fds-gray-100': '#1C1E21',
//   'fds-gray-20': '#DADDE1',
//   'fds-gray-25': '#CCD0D5',
//   'fds-gray-30': '#BEC3C9',
//   'fds-gray-45': '#8D949E',
//   'fds-gray-70': '#606770',
//   'fds-gray-80': '#444950',
//   'fds-gray-90': '#303338',
//   'fds-green-55': '#00A400',
//   'fds-highlight': '#3578E5',
//   'fds-highlight-cell-background': '#ECF3FF',
//   'fds-primary-icon': '#1C1E21',
//   'fds-primary-text': '#1C1E21',
//   'fds-red-55': '#FA383E',
//   'fds-soft': 'cubic-bezier(.08,.52,.52,1)',
//   'fds-spectrum-aluminum-tint-70': '#E4F0F6',
//   'fds-spectrum-blue-gray-tint-70': '#CFD1D5',
//   'fds-spectrum-cherry': '#F35369',
//   'fds-spectrum-cherry-tint-70': '#FBCCD2',
//   'fds-spectrum-grape-tint-70': '#DDD5F0',
//   'fds-spectrum-grape-tint-90': '#F4F1FA',
//   'fds-spectrum-lemon-dark-1': '#F5C33B',
//   'fds-spectrum-lemon-tint-70': '#FEF2D1',
//   'fds-spectrum-lime': '#A3CE71',
//   'fds-spectrum-lime-tint-70': '#E4F0D5',
//   'fds-spectrum-orange-tint-70': '#FCDEC5',
//   'fds-spectrum-orange-tint-90': '#FEF4EC',
//   accent: '#1763CF',
//   'fds-spectrum-seafoam-tint-70': '#CAEEF9',
//   'always-black': 'black',
//   'fds-spectrum-slate-dark-2': '#89A1AC',
//   'always-dark-gradient': 'linear-gradient(rgba(0,0,0,0), rgba(0,0,0,0.6))',
//   'fds-spectrum-slate-tint-70': '#EAEFF2',
//   'always-dark-overlay': 'rgba(0, 0, 0, 0.4)',
//   'fds-spectrum-teal': '#6BCEBB',
//   'always-gray-40': '#65676B',
//   'fds-spectrum-teal-dark-1': '#4DBBA6',
//   'always-gray-75': '#BCC0C4',
//   'fds-spectrum-teal-dark-2': '#31A38D',
//   'always-gray-95': '#F0F2F5',
//   'fds-spectrum-teal-tint-70': '#D2F0EA',
//   'always-light-overlay': 'rgba(255, 255, 255, 0.4)',
//   'fds-spectrum-teal-tint-90': '#F0FAF8',
//   'always-white': '#FFFFFF',
//   'fds-spectrum-tomato': '#FB724B',
//   'attachment-footer-background': '#F0F2F5',
//   'fds-spectrum-tomato-tint-30': '#F38E7B',
//   'background-deemphasized': '#F0F2F5',
//   'fds-spectrum-tomato-tint-90': '#FDEFED',
//   'badge-background-color-blue': 'var(--accent)',
//   'fds-strong': 'cubic-bezier(.12,.8,.32,1)',
//   'badge-background-color-dark-gray': 'var(--secondary-icon)',
//   'fds-white': '#FFFFFF',
//   'badge-background-color-gray': 'var(--disabled-icon)',
//   'fds-white-alpha-05': 'rgba(255, 255, 255, 0.05)',
//   'badge-background-color-green': 'var(--positive)',
//   'fds-white-alpha-10': 'rgba(255, 255, 255, 0.1)',
//   'badge-background-color-light-blue': 'var(--highlight-bg)',
//   'fds-white-alpha-20': 'rgba(255, 255, 255, 0.2)',
//   'badge-background-color-red': 'var(--notification-badge)',
//   'fds-white-alpha-30': 'rgba(255, 255, 255, 0.3)',
//   'badge-background-color-yellow': 'var(--base-lemon)',
//   'fds-white-alpha-40': 'rgba(255, 255, 255, 0.4)',
//   'base-blue': '#1877F2',
//   'fds-white-alpha-50': 'rgba(255, 255, 255, 0.5)',
//   'base-cherry': '#F3425F',
//   'fds-white-alpha-60': 'rgba(255, 255, 255, 0.6)',
//   'base-grape': '#9360F7',
//   'fds-white-alpha-80': 'rgba(255, 255, 255, 0.8)',
//   'base-lemon': '#F7B928',
//   'fds-yellow-20': '#FFBA00',
//   'base-lime': '#45BD62',
//   'base-pink': '#FF66BF',
//   'base-seafoam': '#54C7EC',
//   'base-teal': '#2ABBA7',
//   'base-tomato': '#FB724B',
//   'blue-link': '#216FDB',
//   'border-focused': '#65676B',
//   'card-background': '#FFFFFF',
//   'card-background-flat': '#F7F8FA',
//   'comment-background': '#F0F2F5',
//   'comment-footer-background': '#F6F9FA',
//   'dataviz-primary-1': 'rgb(48,200,180)',
//   'disabled-button-background': '#E4E6EB',
//   'disabled-button-text': '#BCC0C4',
//   'disabled-icon': '#BCC0C4',
//   'disabled-text': '#BCC0C4',
//   divider: '#CED0D4',
//   'event-date': '#F3425F',
//   'fb-logo': '#0866FF',
//   'fb-wordmark': '#0866FF',
//   'filter-accent':
//     'invert(39%) sepia(57%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(147.75%) hue-rotate(202deg) brightness(97%) contrast(96%)',
//   'filter-always-white': 'invert(100%)',
//   'filter-blue-link-icon':
//     'invert(30%) sepia(98%) saturate(200%) saturate(200%) saturate(200%) saturate(166.5%) hue-rotate(192deg) brightness(91%) contrast(101%)',
//   'filter-disabled-icon':
//     'invert(80%) sepia(6%) saturate(200%) saturate(120%) hue-rotate(173deg) brightness(98%) contrast(89%)',
//   'text-badge-attention-background': 'hsl(40, 89%, 52%)',
//   'filter-negative':
//     'invert(25%) sepia(33%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(110%) hue-rotate(345deg) brightness(132%) contrast(96%)',
//   'text-badge-info-background': 'hsl(214, 89%, 52%)',
//   'filter-placeholder-icon':
//     'invert(59%) sepia(11%) saturate(200%) saturate(135%) hue-rotate(176deg) brightness(96%) contrast(94%)',
//   'text-badge-success-background': '#31A24C',
//   'filter-positive':
//     'invert(37%) sepia(61%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(115%) hue-rotate(91deg) brightness(97%) contrast(105%)',
//   'text-badge-critical-background': '#e41e3f',
//   'filter-primary-accent':
//     'invert(39%) sepia(57%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(147.75%) hue-rotate(202deg) brightness(97%) contrast(96%)',
//   'filter-primary-icon':
//     'invert(8%) sepia(10%) saturate(200%) saturate(200%) saturate(166%) hue-rotate(177deg) brightness(104%) contrast(91%)',
//   'filter-secondary-icon':
//     'invert(39%) sepia(21%) saturate(200%) saturate(109.5%) hue-rotate(174deg) brightness(94%) contrast(86%)',
//   'filter-warning-icon':
//     'invert(77%) sepia(29%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(128%) hue-rotate(359deg) brightness(102%) contrast(107%)',
//   'focus-ring-blue': '#1877F2',
//   'glimmer-spinner-icon': '#65676B',
//   'hero-banner-background': '#FFFFFF',
//   'highlight-bg': '#E7F3FF',
//   'hosted-view-selected-state': 'rgba(45, 136, 255, 0.1)',
//   'hover-overlay': 'rgba(0, 0, 0, 0.05)',
//   'list-cell-chevron': '#65676B',
//   'media-hover': 'rgba(68, 73, 80, 0.15)',
//   'media-inner-border': 'rgba(0, 0, 0, 0.1)',
//   'media-outer-border': '#FFFFFF',
//   'media-pressed': 'rgba(68, 73, 80, 0.35)',
//   'messenger-card-background': '#fafbfc',
//   'messenger-reply-background': '#F0F2F5',
//   'nav-bar-background': '#FFFFFF',
//   'nav-bar-background-gradient':
//     'linear-gradient(to top, #FFFFFF, rgba(255,255,255.9), rgba(255,255,255,.7), rgba(255,255,255,.4), rgba(255,255,255,0))',
//   'nav-bar-background-gradient-wash':
//     'linear-gradient(to top, #F0F2F5, rgba(240,242,245.9), rgba(240,242,245,.7), rgba(240,242,245,.4), rgba(240,242,245,0))',
//   negative: 'hsl(350, 87%, 55%)',
//   'negative-background': 'hsl(350, 87%, 55%, 20%)',
//   'new-notification-background': '#f2f3f5',
//   'non-media-pressed': 'rgba(68, 73, 80, 0.15)',
//   'non-media-pressed-on-dark': 'rgba(255, 255, 255, 0.3)',
//   'notification-badge': '#e41e3f',
//   'overlay-alpha-80': 'rgba(244, 244, 244, 0.8)',
//   'overlay-on-media': 'rgba(0, 0, 0, 0.6)',
//   'placeholder-icon': '#65676B',
//   'placeholder-image': 'rgb(164, 167, 171)',
//   'placeholder-text': '#65676B',
//   'placeholder-text-on-media': 'rgba(255, 255, 255, 0.5)',
//   'popover-background': '#FFFFFF',
//   positive: '#31A24C',
//   'positive-background': '#DEEFE1',
//   'press-overlay': 'rgba(0, 0, 0, 0.10)',
//   'primary-button-background': '#1B74E4',
//   'primary-button-icon': '#FFFFFF',
//   'primary-button-pressed': '#77A7FF',
//   'primary-button-text': '#FFFFFF',
//   'primary-deemphasized-button-background': '#E7F3FF',
//   'primary-deemphasized-button-pressed': 'rgba(0, 0, 0, 0.05)',
//   'primary-deemphasized-button-pressed-overlay': 'rgba(25, 110, 255, 0.15)',
//   'primary-deemphasized-button-text': '#1763CF',
//   'primary-icon': '#050505',
//   'primary-text': '#050505',
//   'primary-text-on-media': '#FFFFFF',
//   'primary-web-focus-indicator': '#D24294',
//   'progress-ring-blue-background': 'rgba(24, 119, 242, 0.2)',
//   'progress-ring-blue-foreground': 'hsl(214, 89%, 52%)',
//   'progress-ring-disabled-background': 'rgba(190,195,201, 0.2)',
//   'progress-ring-disabled-foreground': '#BEC3C9',
//   'progress-ring-neutral-background': 'rgba(0, 0, 0, 0.2)',
//   'progress-ring-neutral-foreground': '#000000',
//   'progress-ring-on-media-background': 'rgba(255, 255, 255, 0.2)',
//   'progress-ring-on-media-foreground': '#FFFFFF',
//   'rating-star-active': '#EB660D',
//   'scroll-shadow':
//     '0 1px 2px rgba(0, 0, 0, 0.1), 0 -1px rgba(0, 0, 0, 0.1) inset',
//   'input-background': '#FFFFFF',
//   'scroll-thumb': '#BCC0C4',
//   'input-background-disabled': '#F0F2F5',
//   'secondary-button-background': '#E4E6EB',
//   'input-border-color': '#CED0D4',
//   'secondary-button-background-floating': '#ffffff',
//   'input-border-color-hover': 'var(--placeholder-text)',
//   'secondary-button-background-on-dark': 'rgba(0, 0, 0, 0.4)',
//   'input-label-color-highlighted': '#1B74E4',
//   'secondary-button-pressed': 'rgba(0, 0, 0, 0.05)',
//   'secondary-button-stroke': 'transparent',
//   'secondary-button-text': '#050505',
//   'secondary-icon': '#65676B',
//   'secondary-text': '#65676B',
//   'secondary-text-on-media': 'rgba(255, 255, 255, 0.9)',
//   'section-header-text': '#4B4C4F',
//   'shadow-1': 'rgba(0, 0, 0, 0.1)',
//   'shadow-2': 'rgba(0, 0, 0, 0.2)',
//   'shadow-5': 'rgba(0, 0, 0, 0.5)',
//   'chat-bubble-padding-horizontal': '12px',
//   'shadow-8': 'rgba(0, 0, 0, 0.8)',
//   'chat-bubble-border-radius': '18px',
//   'shadow-elevated':
//     '0 8px 20px 0 rgba(0, 0, 0, 0.2), 0 2px 4px 0 rgba(0, 0, 0, 0.1)',
//   'chat-bubble-padding-vertical': '8px',
//   'shadow-inset': 'rgba(255, 255, 255, 0.5)',
//   'chat-incoming-message-bubble-background-color': '#F0F0F0',
//   'shadow-persistent': '0px 0px 12px rgba(52, 72, 84, 0.05)',
//   'chat-replied-message-background-color': 'rgba(0, 0, 0, 0.03)',
//   'shadow-primary': '0px 5px 12px rgba(52, 72, 84, 0.2)',
//   'chat-text-blockquote-color-background-line': 'rgba(0, 0, 0, 0.12)',
//   'surface-background': '#FFFFFF',
//   'chat-text-blockquote-color-text-primary-media': 'rgba(255, 255, 255, 0.7)',
//   'switch-active': 'hsl(214, 89%, 52%)',
//   'dialog-anchor-vertical-padding': '0px',
//   'text-highlight': 'rgba(24, 119, 242, 0.2)',
//   'fb-logo-color': '#2D88FF',
//   'text-input-outside-label': '#000000',
//   'alert-banner-corner-radius': '8px',
//   'toast-background': '#FFFFFF',
//   'button-corner-radius': '6px',
//   'toast-text': '#1C2B33',
//   'button-corner-radius-large': '12px',
//   'toast-text-link': '#216FDB',
//   'button-corner-radius-medium': '10px',
//   'toggle-active-background': '#E7F3FF',
//   'button-height-large': '40px',
//   'toggle-active-icon': 'rgb(24, 119, 242)',
//   'button-height-medium': '36px',
//   'toggle-active-text': 'rgb(24, 119, 242)',
//   'blueprint-button-height-medium': '40px',
//   'toggle-button-active-background': '#E7F3FF',
//   'blueprint-button-height-large': '48px',
//   'tooltip-background': 'rgba(244, 244, 244, 0.8)',
//   'button-icon-padding-large': '16px',
//   'tooltip-box-shadow': '0 2px 4px 0 var(--shadow-5)',
//   'button-icon-padding-medium': '16px',
//   warning: 'hsl(40, 89%, 52%)',
//   'button-inner-icon-spacing-large': '3px',
//   wash: '#E4E6EB',
//   'button-inner-icon-spacing-medium': '3px',
//   'web-wash': '#fafbfc',
//   'button-padding-horizontal-large': '16px',
//   'button-padding-horizontal-medium': '16px',
//   'global-panel-width': '0px',
//   'card-box-shadow':
//     '0 12px 28px 0 var(--shadow-2), 0 2px 4px 0 var(--shadow-1)',
//   'radio-border-color': 'var(--primary-icon)',
//   'card-corner-radius': '8px',
//   'radio-border-color-disabled': 'var(--disabled-button-background)',
//   'card-padding-horizontal': '10px',
//   'radio-border-color-selected': 'var(--accent)',
//   'card-padding-vertical': '20px',
//   'radio-checked-icon-color': 'var(--accent)',
//   'chip-corner-radius': '6px',
//   'radio-checked-icon-color-disabled': 'var(--disabled-button-background)',
//   'dialog-corner-radius': '8px',
//   'glimmer-corner-radius': '8px',
//   'header-height': '0px',
//   'global-panel-width-expanded': '0px',
//   'image-corner-radius': '4px',
//   'input-border-width': '1px',
//   'input-corner-radius': '6px',
//   'list-cell-corner-radius': '8px',
//   'list-cell-min-height': '52px',
//   'list-cell-padding-vertical': '20px',
//   'list-cell-padding-vertical-with-addon': '14px',
//   'menu-item-base-margin-horizontal': '8px',
//   'menu-item-base-padding-horizontal': '8px',
//   'nav-list-cell-corner-radius': '8px',
//   'nav-list-cell-min-height': '0px',
//   'nav-list-cell-padding-vertical': '16px',
//   'nav-list-cell-padding-vertical-with-addon': '16px',
//   'page-footer-padding-vertical': '16px',
//   'section-header-addOnEnd-button-padding-horizontal': '0px',
//   'section-header-addOnEnd-button-padding-vertical': '0px',
//   'section-header-addOnEnd-margin-horizontal': '8px',
//   'fds-animation-enter-exit-in': 'cubic-bezier(0.14, 1, 0.34, 1)',
//   'section-header-addOnStart-margin-horizontal': '12px',
//   'fds-animation-enter-exit-out': 'cubic-bezier(0.45, 0.1, 0.2, 1)',
//   'section-header-padding-vertical': '16px',
//   'fds-animation-move-in': 'cubic-bezier(0.17, 0.17, 0, 1)',
//   'section-header-subtitle-margin-vertical': '14px',
//   'fds-animation-expand-collapse-in': 'cubic-bezier(0.17, 0.17, 0, 1)',
//   'section-header-subtitle-with-addOnEnd-margin-vertical': '6px',
//   'fds-animation-expand-collapse-out': 'cubic-bezier(0.17, 0.17, 0, 1)',
//   'text-badge-corner-radius': '4px',
//   'fds-animation-move-out': 'cubic-bezier(0.17, 0.17, 0, 1)',
//   'text-badge-padding-horizontal': '6px',
//   'fds-animation-fade-in': 'cubic-bezier(0, 0, 1, 1)',
//   'text-badge-padding-vertical': '6px',
//   'fds-animation-fade-out': 'cubic-bezier(0, 0, 1, 1)',
//   'text-input-caption-margin-top': '10px',
//   'fds-animation-passive-move-in': 'cubic-bezier(0.5, 0, 0.1, 1)',
//   'text-input-label-top': '22px',
//   'fds-animation-passive-move-out': 'cubic-bezier(0.5, 0, 0.1, 1)',
//   'text-input-min-height': '64px',
//   'fds-animation-quick-move-in': 'cubic-bezier(0.1, 0.9, 0.2, 1)',
//   'text-input-multi-padding-between-text-scrollbar': '20px',
//   'fds-animation-quick-move-out': 'cubic-bezier(0.1, 0.9, 0.2, 1)',
//   'text-input-multi-padding-scrollbar': '16px',
//   'fds-animation-swap-shuffle-in': 'cubic-bezier(0.14, 1, 0.34, 1)',
//   'text-input-padding-vertical': '12px',
//   'fds-animation-swap-shuffle-out': 'cubic-bezier(0.45, 0.1, 0.2, 1)',
//   'toast-addon-padding-horizontal': '6px',
//   'fds-duration-extra-extra-short-in': '100ms',
//   'toast-addon-padding-vertical': '6px',
//   'fds-duration-extra-extra-short-out': '100ms',
//   'toast-container-max-width': '100%',
//   'fds-duration-extra-long-in': '1000ms',
//   'toast-container-min-width': '288px',
//   'body-font-family': 'Placeholder Font',
//   'toast-container-padding-horizontal': '10px',
//   'body-font-size': '0.9375rem',
//   'toast-container-padding-vertical': '16px',
//   'body-emphasized-font-family': 'Placeholder Font',
//   'toast-corner-radius': '8px',
//   'body-emphasized-font-size': '0.9375rem',
//   'tooltip-corner-radius': '8px',
//   'body-emphasized-font-weight': '600',
//   'typeahead-list-outer-padding-vertical': '2px',
//   'body-emphasized-line-height': '1.3333',
//   'fds-duration-extra-long-out': '1000ms',
//   'body-font-weight': '400',
//   'fds-duration-extra-short-in': '200ms',
//   'body-line-height': '1.3333',
//   'fds-duration-extra-short-out': '150ms',
//   'fds-duration-long-in': '500ms',
//   'fds-duration-long-out': '350ms',
//   'fds-duration-medium-in': '400ms',
//   'fds-duration-medium-out': '350ms',
//   'fds-duration-none': '0ms',
//   'fds-duration-short-in': '280ms',
//   'fds-duration-short-out': '200ms',
//   'fds-fast': '200ms',
//   'fds-slow': '400ms',
//   'font-family-apple':
//     "system-ui, -apple-system, BlinkMacSystemFont, '.SFNSText-Regular', sans-serif",
//   'font-family-code': 'ui-monospace, Menlo, Consolas, Monaco, monospace',
//   'font-family-default': 'Helvetica, Arial, sans-serif',
//   'font-family-segoe':
//     'Segoe UI Historic, Segoe UI, Helvetica, Arial, sans-serif',
//   'headline1-font-family': 'Optimistic Display Bold, system-ui, sans-serif',
//   'headline1-font-size': '1.75rem',
//   'headline1-font-weight': '700',
//   'headline1-line-height': '1.2143',
//   'headline2-font-family': 'Optimistic Display Bold, system-ui, sans-serif',
//   'headline2-font-size': '1.5rem',
//   'headline2-font-weight': '700',
//   'headline2-line-height': '1.25',
//   'headline3-font-family': 'Optimistic Display Bold, system-ui, sans-serif',
//   'headline3-font-size': '1.0625rem',
//   'headline3-font-weight': '700',
//   'headline3-line-height': '1.2941',
//   'meta-emphasized-font-family': 'Placeholder Font',
//   'meta-emphasized-font-size': '0.8125rem',
//   'meta-emphasized-font-weight': '600',
//   'meta-emphasized-line-height': '1.3846',
//   'meta-font-family': 'Placeholder Font',
//   'meta-font-size': '0.8125rem',
//   'meta-font-weight': '400',
//   'dialog-size-medium-max-width': '700px',
//   'meta-line-height': '1.3846',
//   'dialog-size-medium-width': '100%',
//   'primary-label-font-family':
//     'Optimistic Display Medium, system-ui, sans-serif',
//   'dialog-size-small-max-width': '548px',
//   'primary-label-font-size': '1.0625rem',
//   'dialog-size-small-width': '100%',
//   'primary-label-font-weight': '500',
//   'focus-ring-outline-forced-colors': '2px auto transparent !important',
//   'primary-label-line-height': '1.2941',
//   'focus-ring-outline-link': '2px auto var(--focus-ring-blue)',
//   'secondary-label-font-family': 'Placeholder Font',
//   'focus-ring-shadow-default':
//     '0 0 0 2px var(--always-white), 0 0 0 4px var(--focus-ring-blue)',
//   'secondary-label-font-size': '0.9375rem',
//   'focus-ring-shadow-inset':
//     '0 0 0 2px var(--focus-ring-blue) inset, 0 0 0 4px var(--always-white) inset',
//   'secondary-label-font-weight': '500',
//   'glimmer-animation-direction': 'alternate',
//   'secondary-label-line-height': '1.3333',
//   'dataviz-primary-2': 'rgb(134,218,255)',
//   'tertiary-label-font-family': 'Placeholder Font',
//   'dataviz-primary-3': 'rgb(95,170,255)',
//   'tertiary-label-font-size': '0.6875rem',
//   'dataviz-secondary-1': 'rgb(118,62,230)',
//   'tertiary-label-font-weight': '500',
//   'dataviz-secondary-2': 'rgb(147,96,247)',
//   'tertiary-label-line-height': '1.4545',
//   'dataviz-secondary-3': 'rgb(219,26,139)',
//   'text-input-field-font-family': 'Placeholder Font',
//   'dataviz-supplementary-1': 'rgb(255,122,105)',
//   'text-input-field-font-size': '1rem',
//   'dataviz-supplementary-2': 'rgb(241,168,23)',
//   'text-input-field-font-weight': '500',
//   'dataviz-supplementary-3': 'rgb(49,162,76)',
//   'text-input-field-line-height': '1.2941',
//   'dataviz-supplementary-4': 'rgb(50,52,54)',
//   'text-input-label-font-family': 'Placeholder Font',
//   'glimmer-animation-duration': '1000ms',
//   'text-input-label-font-size': '17px',
//   'glimmer-animation-timing-function': 'steps(10, end)',
//   'text-input-label-font-size-scale-multiplier': '0.75',
//   'glimmer-opacity-max': '1',
//   'text-input-label-font-weight': '400',
//   'glimmer-opacity-min': '0.25',
//   'text-input-label-line-height': '1.2941',
//   'radio-border-width': '2px',
//   'radio-checked-icon-size-large': '12px',
//   'radio-checked-icon-size-medium': '12px',
//   'radio-size-large': '24px',
//   'radio-size-medium': '20px',
//   'wig-blue': '#1763CF',
//   'wig-blue-black-20': '#1060c8',
//   'wig-blue-black-40': '#0d54af',
//   'wig-blue-button': '#1B74E4',
//   'wig-blue-white-70': '#b8d7fd',
//   'wig-blue-white-90': '#e7f1fe',
//   'wig-desktop-wash': '#ebe9e7',
//   'wig-coral': '#ff645a',
//   'wig-grey': '#373e4c',
//   'wig-aqua': '#64d2d2',
//   'wig-oyster': '#ece9e7',
//   'wig-cherry': '#e62546',
//   'wig-oyster-black-05': '#dfdddb',
//   'wig-blush': '#f0c8a0',
//   'wig-oyster-black-10': '#d3d1cf',
//   'wig-green': '#42b72a',
//   'wig-oyster-black-20': '#bcbab8',
//   'wig-black-alpha-05': 'rgba(0, 0, 0, 0.05)',
//   'wig-oyster-black-40': '#8d8b8a',
//   'wig-black-alpha-10': 'rgba(0, 0, 0, 0.1)',
//   'wig-oyster-white-25': '#f0eeec',
//   'wig-grass': '#77b526',
//   'wig-oyster-white-40': '#f3f1f0',
//   'wig-hovered-background': 'rgba(0, 0, 0, 0.05)',
//   'wig-oyster-white-50': '#f7f6f5',
//   'wig-input-background': '#f2f3f5',
//   'wig-oyster-white-60': '#f2f1f0',
//   'wig-divider': '#E1E1E2',
//   'wig-oyster-black-50': '#757473',
//   'fds-www-wash': '#EBEDF0',
//   'wig-oyster-black-60': '#555453',
//   'wig-chat-background': '#FFFFFF',
//   'wig-oyster-black-70': '#474645',
//   'wig-chat-bubble-sender': '#f2f3f5',
//   'wig-oyster-black-85': '#232222',
//   'wig-chat-bubble': '#373e4c',
//   'wig-light-grey': '#ebedf0',
//   'wig-chat-default-color': '#373e4c',
//   'wig-white': '#ffffff',
//   'wig-channel-icon-default-background': '#373e4c',
//   'wig-contrast-background': '#FFFFFF',
//   'wig-khaki': '#c4c078',
//   'wig-foreign-entity': '#B11710',
//   'wig-orange': '#ff8216',
//   'wig-group-cover-default-background': '#373e4c',
//   'wig-red': '#fa3e3e',
//   'tasks-priority-high': '#f23232',
//   'wig-purple': '#9678d2',
//   'tasks-priority-low': '#eec954',
//   'tasks-priority-mid': '#f88639',
//   'wig-yellow': '#f0c850',
//   'tasks-priority-none': '#c4d2e7',
//   'wig-pink': '#ffb4c8',
//   'tasks-priority-unbreak': '#8036cc',
//   'wig-sky': '#50b4f0',
//   'tasks-priority-wish': '#5cc9b4',
//   'wig-teal': '#00c882',
//   'wig-iris-100': '#4326C4',
//   'wig-mushroom-120': '#896674',
//   'wig-nav-background': '#fafbfc',
//   'wig-nav-channel-gradient':
//     'linear-gradient(90deg, rgba(0,0,0,0.0), rgba(0,0,0,0.02))',
//   'wig-page-background': '#fafbfc',
//   'wig-official-entity': '#00c882',
//   'wig-selected-background': 'rgba(0, 0, 0, 0.1)',
//   'wig-primary-iris-90': '#573bd3',
//   'wig-quick-chat-settings-shadow-end': 'rgba(0, 0, 0, 0.3)',
//   'wig-quick-chat-settings-shadow-start': 'rgba(0, 0, 0, 0.1)',
//   'workplace-chart-background': '#ECF3FF',
//   'workplace-chart-caption': '#FFFFFF',
//   'workplace-chart-foreground': '#C2DCFC',
// };

// const lightTheme = {
//   'fds-black': '#000000',
//   'fds-black-alpha-05': 'rgba(0, 0, 0, 0.05)',
//   'fds-black-alpha-10': 'rgba(0, 0, 0, 0.1)',
//   'fds-black-alpha-15': 'rgba(0, 0, 0, 0.15)',
//   'fds-black-alpha-20': 'rgba(0, 0, 0, 0.2)',
//   'fds-black-alpha-30': 'rgba(0, 0, 0, 0.3)',
//   'fds-black-alpha-40': 'rgba(0, 0, 0, 0.4)',
//   'fds-black-alpha-50': 'rgba(0, 0, 0, 0.5)',
//   'fds-black-alpha-60': 'rgba(0, 0, 0, 0.6)',
//   'fds-black-alpha-80': 'rgba(0, 0, 0, 0.8)',
//   'fds-blue-05': '#ECF3FF',
//   'fds-blue-30': '#AAC9FF',
//   'fds-blue-40': '#77A7FF',
//   'fds-blue-60': '#1877F2',
//   'fds-blue-70': '#2851A3',
//   'fds-blue-80': '#1D3C78',
//   'fds-button-text': '#444950',
//   'fds-comment-background': '#F2F3F5',
//   'fds-dark-mode-gray-100': '#1C1C1C',
//   'fds-dark-mode-gray-35': '#CCCCCC',
//   'fds-dark-mode-gray-50': '#828282',
//   'fds-dark-mode-gray-70': '#4A4A4A',
//   'fds-dark-mode-gray-80': '#373737',
//   'fds-dark-mode-gray-90': '#282828',
//   'fds-gray-00': '#F5F6F7',
//   'fds-gray-05': '#F2F3F5',
//   'fds-gray-10': '#EBEDF0',
//   'fds-gray-100': '#1C1E21',
//   'fds-gray-20': '#DADDE1',
//   'fds-gray-25': '#CCD0D5',
//   'fds-gray-30': '#BEC3C9',
//   'fds-gray-45': '#8D949E',
//   'fds-gray-70': '#606770',
//   'fds-gray-80': '#444950',
//   'fds-gray-90': '#303338',
//   'fds-green-55': '#00A400',
//   'fds-highlight': '#3578E5',
//   'fds-highlight-cell-background': '#ECF3FF',
//   'fds-primary-icon': '#1C1E21',
//   'fds-primary-text': '#1C1E21',
//   'fds-red-55': '#FA383E',
//   'fds-soft': 'cubic-bezier(.08,.52,.52,1)',
//   'fds-spectrum-aluminum-tint-70': '#E4F0F6',
//   'fds-spectrum-blue-gray-tint-70': '#CFD1D5',
//   'fds-spectrum-cherry': '#F35369',
//   'fds-spectrum-cherry-tint-70': '#FBCCD2',
//   'fds-spectrum-grape-tint-70': '#DDD5F0',
//   'fds-spectrum-grape-tint-90': '#F4F1FA',
//   'fds-spectrum-lemon-dark-1': '#F5C33B',
//   'fds-spectrum-lemon-tint-70': '#FEF2D1',
//   'fds-spectrum-lime': '#A3CE71',
//   'fds-spectrum-lime-tint-70': '#E4F0D5',
//   'fds-spectrum-orange-tint-70': '#FCDEC5',
//   'fds-spectrum-orange-tint-90': '#FEF4EC',
//   accent: '#1763CF',
//   'fds-spectrum-seafoam-tint-70': '#CAEEF9',
//   'always-black': 'black',
//   'fds-spectrum-slate-dark-2': '#89A1AC',
//   'always-dark-gradient': 'linear-gradient(rgba(0,0,0,0), rgba(0,0,0,0.6))',
//   'fds-spectrum-slate-tint-70': '#EAEFF2',
//   'always-dark-overlay': 'rgba(0, 0, 0, 0.4)',
//   'fds-spectrum-teal': '#6BCEBB',
//   'always-gray-40': '#65676B',
//   'fds-spectrum-teal-dark-1': '#4DBBA6',
//   'always-gray-75': '#BCC0C4',
//   'fds-spectrum-teal-dark-2': '#31A38D',
//   'always-gray-95': '#F0F2F5',
//   'fds-spectrum-teal-tint-70': '#D2F0EA',
//   'always-light-overlay': 'rgba(255, 255, 255, 0.4)',
//   'fds-spectrum-teal-tint-90': '#F0FAF8',
//   'always-white': '#FFFFFF',
//   'fds-spectrum-tomato': '#FB724B',
//   'attachment-footer-background': '#F0F2F5',
//   'fds-spectrum-tomato-tint-30': '#F38E7B',
//   'background-deemphasized': '#F0F2F5',
//   'fds-spectrum-tomato-tint-90': '#FDEFED',
//   'badge-background-color-blue': 'var(--accent)',
//   'fds-strong': 'cubic-bezier(.12,.8,.32,1)',
//   'badge-background-color-dark-gray': 'var(--secondary-icon)',
//   'fds-white': '#FFFFFF',
//   'badge-background-color-gray': 'var(--disabled-icon)',
//   'fds-white-alpha-05': 'rgba(255, 255, 255, 0.05)',
//   'badge-background-color-green': 'var(--positive)',
//   'fds-white-alpha-10': 'rgba(255, 255, 255, 0.1)',
//   'badge-background-color-light-blue': 'var(--highlight-bg)',
//   'fds-white-alpha-20': 'rgba(255, 255, 255, 0.2)',
//   'badge-background-color-red': 'var(--notification-badge)',
//   'fds-white-alpha-30': 'rgba(255, 255, 255, 0.3)',
//   'badge-background-color-yellow': 'var(--base-lemon)',
//   'fds-white-alpha-40': 'rgba(255, 255, 255, 0.4)',
//   'base-blue': '#1877F2',
//   'fds-white-alpha-50': 'rgba(255, 255, 255, 0.5)',
//   'base-cherry': '#F3425F',
//   'fds-white-alpha-60': 'rgba(255, 255, 255, 0.6)',
//   'base-grape': '#9360F7',
//   'fds-white-alpha-80': 'rgba(255, 255, 255, 0.8)',
//   'base-lemon': '#F7B928',
//   'fds-yellow-20': '#FFBA00',
//   'base-lime': '#45BD62',
//   'base-pink': '#FF66BF',
//   'base-seafoam': '#54C7EC',
//   'base-teal': '#2ABBA7',
//   'base-tomato': '#FB724B',
//   'blue-link': '#216FDB',
//   'border-focused': '#65676B',
//   'card-background': '#FFFFFF',
//   'card-background-flat': '#F7F8FA',
//   'comment-background': '#F0F2F5',
//   'comment-footer-background': '#F6F9FA',
//   'dataviz-primary-1': 'rgb(48,200,180)',
//   'disabled-button-background': '#E4E6EB',
//   'disabled-button-text': '#BCC0C4',
//   'disabled-icon': '#BCC0C4',
//   'disabled-text': '#BCC0C4',
//   divider: '#CED0D4',
//   'event-date': '#F3425F',
//   'fb-logo': '#0866FF',
//   'fb-wordmark': '#0866FF',
//   'filter-accent':
//     'invert(39%) sepia(57%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(147.75%) hue-rotate(202deg) brightness(97%) contrast(96%)',
//   'filter-always-white': 'invert(100%)',
//   'filter-blue-link-icon':
//     'invert(30%) sepia(98%) saturate(200%) saturate(200%) saturate(200%) saturate(166.5%) hue-rotate(192deg) brightness(91%) contrast(101%)',
//   'filter-disabled-icon':
//     'invert(80%) sepia(6%) saturate(200%) saturate(120%) hue-rotate(173deg) brightness(98%) contrast(89%)',
//   'text-badge-attention-background': 'hsl(40, 89%, 52%)',
//   'filter-negative':
//     'invert(25%) sepia(33%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(110%) hue-rotate(345deg) brightness(132%) contrast(96%)',
//   'text-badge-info-background': 'hsl(214, 89%, 52%)',
//   'filter-placeholder-icon':
//     'invert(59%) sepia(11%) saturate(200%) saturate(135%) hue-rotate(176deg) brightness(96%) contrast(94%)',
//   'text-badge-success-background': '#31A24C',
//   'filter-positive':
//     'invert(37%) sepia(61%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(115%) hue-rotate(91deg) brightness(97%) contrast(105%)',
//   'text-badge-critical-background': '#e41e3f',
//   'filter-primary-accent':
//     'invert(39%) sepia(57%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(147.75%) hue-rotate(202deg) brightness(97%) contrast(96%)',
//   'filter-primary-icon':
//     'invert(8%) sepia(10%) saturate(200%) saturate(200%) saturate(166%) hue-rotate(177deg) brightness(104%) contrast(91%)',
//   'filter-secondary-icon':
//     'invert(39%) sepia(21%) saturate(200%) saturate(109.5%) hue-rotate(174deg) brightness(94%) contrast(86%)',
//   'filter-warning-icon':
//     'invert(77%) sepia(29%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(128%) hue-rotate(359deg) brightness(102%) contrast(107%)',
//   'focus-ring-blue': '#1877F2',
//   'glimmer-spinner-icon': '#65676B',
//   'hero-banner-background': '#FFFFFF',
//   'highlight-bg': '#E7F3FF',
//   'hosted-view-selected-state': 'rgba(45, 136, 255, 0.1)',
//   'hover-overlay': 'rgba(0, 0, 0, 0.05)',
//   'list-cell-chevron': '#65676B',
//   'media-hover': 'rgba(68, 73, 80, 0.15)',
//   'media-inner-border': 'rgba(0, 0, 0, 0.1)',
//   'media-outer-border': '#FFFFFF',
//   'media-pressed': 'rgba(68, 73, 80, 0.35)',
//   'messenger-card-background': '#fafbfc',
//   'messenger-reply-background': '#F0F2F5',
//   'nav-bar-background': '#FFFFFF',
//   'nav-bar-background-gradient':
//     'linear-gradient(to top, #FFFFFF, rgba(255,255,255.9), rgba(255,255,255,.7), rgba(255,255,255,.4), rgba(255,255,255,0))',
//   'nav-bar-background-gradient-wash':
//     'linear-gradient(to top, #F0F2F5, rgba(240,242,245.9), rgba(240,242,245,.7), rgba(240,242,245,.4), rgba(240,242,245,0))',
//   negative: 'hsl(350, 87%, 55%)',
//   'negative-background': 'hsl(350, 87%, 55%, 20%)',
//   'new-notification-background': '#f2f3f5',
//   'non-media-pressed': 'rgba(68, 73, 80, 0.15)',
//   'non-media-pressed-on-dark': 'rgba(255, 255, 255, 0.3)',
//   'notification-badge': '#e41e3f',
//   'overlay-alpha-80': 'rgba(244, 244, 244, 0.8)',
//   'overlay-on-media': 'rgba(0, 0, 0, 0.6)',
//   'placeholder-icon': '#65676B',
//   'placeholder-image': 'rgb(164, 167, 171)',
//   'placeholder-text': '#65676B',
//   'placeholder-text-on-media': 'rgba(255, 255, 255, 0.5)',
//   'popover-background': '#FFFFFF',
//   positive: '#31A24C',
//   'positive-background': '#DEEFE1',
//   'press-overlay': 'rgba(0, 0, 0, 0.10)',
//   'primary-button-background': '#1B74E4',
//   'primary-button-icon': '#FFFFFF',
//   'primary-button-pressed': '#77A7FF',
//   'primary-button-text': '#FFFFFF',
//   'primary-deemphasized-button-background': '#E7F3FF',
//   'primary-deemphasized-button-pressed': 'rgba(0, 0, 0, 0.05)',
//   'primary-deemphasized-button-pressed-overlay': 'rgba(25, 110, 255, 0.15)',
//   'primary-deemphasized-button-text': '#1763CF',
//   'primary-icon': '#050505',
//   'primary-text': '#050505',
//   'primary-text-on-media': '#FFFFFF',
//   'primary-web-focus-indicator': '#D24294',
//   'progress-ring-blue-background': 'rgba(24, 119, 242, 0.2)',
//   'progress-ring-blue-foreground': 'hsl(214, 89%, 52%)',
//   'progress-ring-disabled-background': 'rgba(190,195,201, 0.2)',
//   'progress-ring-disabled-foreground': '#BEC3C9',
//   'progress-ring-neutral-background': 'rgba(0, 0, 0, 0.2)',
//   'progress-ring-neutral-foreground': '#000000',
//   'progress-ring-on-media-background': 'rgba(255, 255, 255, 0.2)',
//   'progress-ring-on-media-foreground': '#FFFFFF',
//   'rating-star-active': '#EB660D',
//   'scroll-shadow':
//     '0 1px 2px rgba(0, 0, 0, 0.1), 0 -1px rgba(0, 0, 0, 0.1) inset',
//   'input-background': '#FFFFFF',
//   'scroll-thumb': '#BCC0C4',
//   'input-background-disabled': '#F0F2F5',
//   'secondary-button-background': '#E4E6EB',
//   'input-border-color': '#CED0D4',
//   'secondary-button-background-floating': '#ffffff',
//   'input-border-color-hover': 'var(--placeholder-text)',
//   'secondary-button-background-on-dark': 'rgba(0, 0, 0, 0.4)',
//   'input-label-color-highlighted': '#1B74E4',
//   'secondary-button-pressed': 'rgba(0, 0, 0, 0.05)',
//   'secondary-button-stroke': 'transparent',
//   'secondary-button-text': '#050505',
//   'secondary-icon': '#65676B',
//   'secondary-text': '#65676B',
//   'secondary-text-on-media': 'rgba(255, 255, 255, 0.9)',
//   'section-header-text': '#4B4C4F',
//   'shadow-1': 'rgba(0, 0, 0, 0.1)',
//   'shadow-2': 'rgba(0, 0, 0, 0.2)',
//   'shadow-5': 'rgba(0, 0, 0, 0.5)',
//   'chat-bubble-padding-horizontal': '12px',
//   'shadow-8': 'rgba(0, 0, 0, 0.8)',
//   'chat-bubble-border-radius': '18px',
//   'shadow-elevated':
//     '0 8px 20px 0 rgba(0, 0, 0, 0.2), 0 2px 4px 0 rgba(0, 0, 0, 0.1)',
//   'chat-bubble-padding-vertical': '8px',
//   'shadow-inset': 'rgba(255, 255, 255, 0.5)',
//   'chat-incoming-message-bubble-background-color': '#F0F0F0',
//   'shadow-persistent': '0px 0px 12px rgba(52, 72, 84, 0.05)',
//   'chat-replied-message-background-color': 'rgba(0, 0, 0, 0.03)',
//   'shadow-primary': '0px 5px 12px rgba(52, 72, 84, 0.2)',
//   'chat-text-blockquote-color-background-line': 'rgba(0, 0, 0, 0.12)',
//   'surface-background': '#FFFFFF',
//   'chat-text-blockquote-color-text-primary-media': 'rgba(255, 255, 255, 0.7)',
//   'switch-active': 'hsl(214, 89%, 52%)',
//   'dialog-anchor-vertical-padding': '0px',
//   'text-highlight': 'rgba(24, 119, 242, 0.2)',
//   'fb-logo-color': '#2D88FF',
//   'text-input-outside-label': '#000000',
//   'alert-banner-corner-radius': '8px',
//   'toast-background': '#FFFFFF',
//   'button-corner-radius': '6px',
//   'toast-text': '#1C2B33',
//   'button-corner-radius-large': '12px',
//   'toast-text-link': '#216FDB',
//   'button-corner-radius-medium': '10px',
//   'toggle-active-background': '#E7F3FF',
//   'button-height-large': '40px',
//   'toggle-active-icon': 'rgb(24, 119, 242)',
//   'button-height-medium': '36px',
//   'toggle-active-text': 'rgb(24, 119, 242)',
//   'blueprint-button-height-medium': '40px',
//   'toggle-button-active-background': '#E7F3FF',
//   'blueprint-button-height-large': '48px',
//   'tooltip-background': 'rgba(244, 244, 244, 0.8)',
//   'button-icon-padding-large': '16px',
//   'tooltip-box-shadow': '0 2px 4px 0 var(--shadow-5)',
//   'button-icon-padding-medium': '16px',
//   warning: 'hsl(40, 89%, 52%)',
//   'button-inner-icon-spacing-large': '3px',
//   wash: '#E4E6EB',
//   'button-inner-icon-spacing-medium': '3px',
//   'web-wash': '#fafbfc',
//   'button-padding-horizontal-large': '16px',
//   'button-padding-horizontal-medium': '16px',
//   'global-panel-width': '0px',
//   'card-box-shadow':
//     '0 12px 28px 0 var(--shadow-2), 0 2px 4px 0 var(--shadow-1)',
//   'radio-border-color': 'var(--primary-icon)',
//   'card-corner-radius': '8px',
//   'radio-border-color-disabled': 'var(--disabled-button-background)',
//   'card-padding-horizontal': '10px',
//   'radio-border-color-selected': 'var(--accent)',
//   'card-padding-vertical': '20px',
//   'radio-checked-icon-color': 'var(--accent)',
//   'chip-corner-radius': '6px',
//   'radio-checked-icon-color-disabled': 'var(--disabled-button-background)',
//   'dialog-corner-radius': '8px',
//   'glimmer-corner-radius': '8px',
//   'header-height': '0px',
//   'global-panel-width-expanded': '0px',
//   'image-corner-radius': '4px',
//   'input-border-width': '1px',
//   'input-corner-radius': '6px',
//   'list-cell-corner-radius': '8px',
//   'list-cell-min-height': '52px',
//   'list-cell-padding-vertical': '20px',
//   'list-cell-padding-vertical-with-addon': '14px',
//   'menu-item-base-margin-horizontal': '8px',
//   'menu-item-base-padding-horizontal': '8px',
//   'nav-list-cell-corner-radius': '8px',
//   'nav-list-cell-min-height': '0px',
//   'nav-list-cell-padding-vertical': '16px',
//   'nav-list-cell-padding-vertical-with-addon': '16px',
//   'page-footer-padding-vertical': '16px',
//   'section-header-addOnEnd-button-padding-horizontal': '0px',
//   'section-header-addOnEnd-button-padding-vertical': '0px',
//   'section-header-addOnEnd-margin-horizontal': '8px',
//   'fds-animation-enter-exit-in': 'cubic-bezier(0.14, 1, 0.34, 1)',
//   'section-header-addOnStart-margin-horizontal': '12px',
//   'fds-animation-enter-exit-out': 'cubic-bezier(0.45, 0.1, 0.2, 1)',
//   'section-header-padding-vertical': '16px',
//   'fds-animation-move-in': 'cubic-bezier(0.17, 0.17, 0, 1)',
//   'section-header-subtitle-margin-vertical': '14px',
//   'fds-animation-expand-collapse-in': 'cubic-bezier(0.17, 0.17, 0, 1)',
//   'section-header-subtitle-with-addOnEnd-margin-vertical': '6px',
//   'fds-animation-expand-collapse-out': 'cubic-bezier(0.17, 0.17, 0, 1)',
//   'text-badge-corner-radius': '4px',
//   'fds-animation-move-out': 'cubic-bezier(0.17, 0.17, 0, 1)',
//   'text-badge-padding-horizontal': '6px',
//   'fds-animation-fade-in': 'cubic-bezier(0, 0, 1, 1)',
//   'text-badge-padding-vertical': '6px',
//   'fds-animation-fade-out': 'cubic-bezier(0, 0, 1, 1)',
//   'text-input-caption-margin-top': '10px',
//   'fds-animation-passive-move-in': 'cubic-bezier(0.5, 0, 0.1, 1)',
//   'text-input-label-top': '22px',
//   'fds-animation-passive-move-out': 'cubic-bezier(0.5, 0, 0.1, 1)',
//   'text-input-min-height': '64px',
//   'fds-animation-quick-move-in': 'cubic-bezier(0.1, 0.9, 0.2, 1)',
//   'text-input-multi-padding-between-text-scrollbar': '20px',
//   'fds-animation-quick-move-out': 'cubic-bezier(0.1, 0.9, 0.2, 1)',
//   'text-input-multi-padding-scrollbar': '16px',
//   'fds-animation-swap-shuffle-in': 'cubic-bezier(0.14, 1, 0.34, 1)',
//   'text-input-padding-vertical': '12px',
//   'fds-animation-swap-shuffle-out': 'cubic-bezier(0.45, 0.1, 0.2, 1)',
//   'toast-addon-padding-horizontal': '6px',
//   'fds-duration-extra-extra-short-in': '100ms',
//   'toast-addon-padding-vertical': '6px',
//   'fds-duration-extra-extra-short-out': '100ms',
//   'toast-container-max-width': '100%',
//   'fds-duration-extra-long-in': '1000ms',
//   'toast-container-min-width': '288px',
//   'body-font-family': 'Placeholder Font',
//   'toast-container-padding-horizontal': '10px',
//   'body-font-size': '0.9375rem',
//   'toast-container-padding-vertical': '16px',
//   'body-emphasized-font-family': 'Placeholder Font',
//   'toast-corner-radius': '8px',
//   'body-emphasized-font-size': '0.9375rem',
//   'tooltip-corner-radius': '8px',
//   'body-emphasized-font-weight': '600',
//   'typeahead-list-outer-padding-vertical': '2px',
//   'body-emphasized-line-height': '1.3333',
//   'fds-duration-extra-long-out': '1000ms',
//   'body-font-weight': '400',
//   'fds-duration-extra-short-in': '200ms',
//   'body-line-height': '1.3333',
//   'fds-duration-extra-short-out': '150ms',
//   'fds-duration-long-in': '500ms',
//   'fds-duration-long-out': '350ms',
//   'fds-duration-medium-in': '400ms',
//   'fds-duration-medium-out': '350ms',
//   'fds-duration-none': '0ms',
//   'fds-duration-short-in': '280ms',
//   'fds-duration-short-out': '200ms',
//   'fds-fast': '200ms',
//   'fds-slow': '400ms',
//   'font-family-apple':
//     "system-ui, -apple-system, BlinkMacSystemFont, '.SFNSText-Regular', sans-serif",
//   'font-family-code': 'ui-monospace, Menlo, Consolas, Monaco, monospace',
//   'font-family-default': 'Helvetica, Arial, sans-serif',
//   'font-family-segoe':
//     'Segoe UI Historic, Segoe UI, Helvetica, Arial, sans-serif',
//   'headline1-font-family': 'Optimistic Display Bold, system-ui, sans-serif',
//   'headline1-font-size': '1.75rem',
//   'headline1-font-weight': '700',
//   'headline1-line-height': '1.2143',
//   'headline2-font-family': 'Optimistic Display Bold, system-ui, sans-serif',
//   'headline2-font-size': '1.5rem',
//   'headline2-font-weight': '700',
//   'headline2-line-height': '1.25',
//   'headline3-font-family': 'Optimistic Display Bold, system-ui, sans-serif',
//   'headline3-font-size': '1.0625rem',
//   'headline3-font-weight': '700',
//   'headline3-line-height': '1.2941',
//   'meta-emphasized-font-family': 'Placeholder Font',
//   'meta-emphasized-font-size': '0.8125rem',
//   'meta-emphasized-font-weight': '600',
//   'meta-emphasized-line-height': '1.3846',
//   'meta-font-family': 'Placeholder Font',
//   'meta-font-size': '0.8125rem',
//   'meta-font-weight': '400',
//   'dialog-size-medium-max-width': '700px',
//   'meta-line-height': '1.3846',
//   'dialog-size-medium-width': '100%',
//   'primary-label-font-family':
//     'Optimistic Display Medium, system-ui, sans-serif',
//   'dialog-size-small-max-width': '548px',
//   'primary-label-font-size': '1.0625rem',
//   'dialog-size-small-width': '100%',
//   'primary-label-font-weight': '500',
//   'focus-ring-outline-forced-colors': '2px auto transparent !important',
//   'primary-label-line-height': '1.2941',
//   'focus-ring-outline-link': '2px auto var(--focus-ring-blue)',
//   'secondary-label-font-family': 'Placeholder Font',
//   'focus-ring-shadow-default':
//     '0 0 0 2px var(--always-white), 0 0 0 4px var(--focus-ring-blue)',
//   'secondary-label-font-size': '0.9375rem',
//   'focus-ring-shadow-inset':
//     '0 0 0 2px var(--focus-ring-blue) inset, 0 0 0 4px var(--always-white) inset',
//   'secondary-label-font-weight': '500',
//   'glimmer-animation-direction': 'alternate',
//   'secondary-label-line-height': '1.3333',
//   'dataviz-primary-2': 'rgb(134,218,255)',
//   'tertiary-label-font-family': 'Placeholder Font',
//   'dataviz-primary-3': 'rgb(95,170,255)',
//   'tertiary-label-font-size': '0.6875rem',
//   'dataviz-secondary-1': 'rgb(118,62,230)',
//   'tertiary-label-font-weight': '500',
//   'dataviz-secondary-2': 'rgb(147,96,247)',
//   'tertiary-label-line-height': '1.4545',
//   'dataviz-secondary-3': 'rgb(219,26,139)',
//   'text-input-field-font-family': 'Placeholder Font',
//   'dataviz-supplementary-1': 'rgb(255,122,105)',
//   'text-input-field-font-size': '1rem',
//   'dataviz-supplementary-2': 'rgb(241,168,23)',
//   'text-input-field-font-weight': '500',
//   'dataviz-supplementary-3': 'rgb(49,162,76)',
//   'text-input-field-line-height': '1.2941',
//   'dataviz-supplementary-4': 'rgb(50,52,54)',
//   'text-input-label-font-family': 'Placeholder Font',
//   'glimmer-animation-duration': '1000ms',
//   'text-input-label-font-size': '17px',
//   'glimmer-animation-timing-function': 'steps(10, end)',
//   'text-input-label-font-size-scale-multiplier': '0.75',
//   'glimmer-opacity-max': '1',
//   'text-input-label-font-weight': '400',
//   'glimmer-opacity-min': '0.25',
//   'text-input-label-line-height': '1.2941',
//   'radio-border-width': '2px',
//   'radio-checked-icon-size-large': '12px',
//   'radio-checked-icon-size-medium': '12px',
//   'radio-size-large': '24px',
//   'radio-size-medium': '20px',
//   'wig-blue': '#1763CF',
//   'wig-blue-black-20': '#1060c8',
//   'wig-blue-black-40': '#0d54af',
//   'wig-blue-button': '#1B74E4',
//   'wig-blue-white-70': '#b8d7fd',
//   'wig-blue-white-90': '#e7f1fe',
//   'wig-desktop-wash': '#ebe9e7',
//   'wig-coral': '#ff645a',
//   'wig-grey': '#373e4c',
//   'wig-aqua': '#64d2d2',
//   'wig-oyster': '#ece9e7',
//   'wig-cherry': '#e62546',
//   'wig-oyster-black-05': '#dfdddb',
//   'wig-blush': '#f0c8a0',
//   'wig-oyster-black-10': '#d3d1cf',
//   'wig-green': '#42b72a',
//   'wig-oyster-black-20': '#bcbab8',
//   'wig-black-alpha-05': 'rgba(0, 0, 0, 0.05)',
//   'wig-oyster-black-40': '#8d8b8a',
//   'wig-black-alpha-10': 'rgba(0, 0, 0, 0.1)',
//   'wig-oyster-white-25': '#f0eeec',
//   'wig-grass': '#77b526',
//   'wig-oyster-white-40': '#f3f1f0',
//   'wig-hovered-background': 'rgba(0, 0, 0, 0.05)',
//   'wig-oyster-white-50': '#f7f6f5',
//   'wig-input-background': '#f2f3f5',
//   'wig-oyster-white-60': '#f2f1f0',
//   'wig-divider': '#E1E1E2',
//   'wig-oyster-black-50': '#757473',
//   'fds-www-wash': '#EBEDF0',
//   'wig-oyster-black-60': '#555453',
//   'wig-chat-background': '#FFFFFF',
//   'wig-oyster-black-70': '#474645',
//   'wig-chat-bubble-sender': '#f2f3f5',
//   'wig-oyster-black-85': '#232222',
//   'wig-chat-bubble': '#373e4c',
//   'wig-light-grey': '#ebedf0',
//   'wig-chat-default-color': '#373e4c',
//   'wig-white': '#ffffff',
//   'wig-channel-icon-default-background': '#373e4c',
//   'wig-contrast-background': '#FFFFFF',
//   'wig-khaki': '#c4c078',
//   'wig-foreign-entity': '#B11710',
//   'wig-orange': '#ff8216',
//   'wig-group-cover-default-background': '#373e4c',
//   'wig-red': '#fa3e3e',
//   'tasks-priority-high': '#f23232',
//   'wig-purple': '#9678d2',
//   'tasks-priority-low': '#eec954',
//   'tasks-priority-mid': '#f88639',
//   'wig-yellow': '#f0c850',
//   'tasks-priority-none': '#c4d2e7',
//   'wig-pink': '#ffb4c8',
//   'tasks-priority-unbreak': '#8036cc',
//   'wig-sky': '#50b4f0',
//   'tasks-priority-wish': '#5cc9b4',
//   'wig-teal': '#00c882',
//   'wig-iris-100': '#4326C4',
//   'wig-mushroom-120': '#896674',
//   'wig-nav-background': '#fafbfc',
//   'wig-nav-channel-gradient':
//     'linear-gradient(90deg, rgba(0,0,0,0.0), rgba(0,0,0,0.02))',
//   'wig-page-background': '#fafbfc',
//   'wig-official-entity': '#00c882',
//   'wig-selected-background': 'rgba(0, 0, 0, 0.1)',
//   'wig-primary-iris-90': '#573bd3',
//   'wig-quick-chat-settings-shadow-end': 'rgba(0, 0, 0, 0.3)',
//   'wig-quick-chat-settings-shadow-start': 'rgba(0, 0, 0, 0.1)',
//   'workplace-chart-background': '#ECF3FF',
//   'workplace-chart-caption': '#FFFFFF',
//   'workplace-chart-foreground': '#C2DCFC',
// };

// // const DARK = '@media (prefers-color-scheme: dark)';

// const tokens = {};

// Object.entries(lightTheme).map(([key, val]) => {
//   tokens[`${key}`] = {
//     default: val,
//   };
// });

// Object.entries(darkTheme).map(([key, val]) => {
//   if (tokens[`${key}`]) {
//     tokens[`${key}`].DARK = val;
//   } else {
//     tokens[`${key}`] = {
//       DARK: val,
//     };
//   }
// });

// const json = JSON.stringify(tokens);

// fs.writeFile('myjsonfile.json', json, 'utf8', () => { });
