export const ICONS = {
  491228: {
    sprited: 2,
    spi: '/faang/assets/icon-list/XvqMI3OqoSa.png',
    _spi: '/faang/assets/icon-list/XvqMI3OqoSa.png',
    w: 20,
    h: 20,
    p: '0 -570px',
    sz: 'auto',
  },
  491223: {
    sprited: 2,
    spi: '/faang/assets/icon-list/XvqMI3OqoSa.png',
    _spi: '/faang/assets/icon-list/XvqMI3OqoSa.png',
    w: 20,
    h: 20,
    p: '0 -549px',
    sz: 'auto',
  },
  1739808: {
    sprited: 2,
    spi: '/faang/assets/icon-list/XvqMI3OqoSa.png',
    _spi: '/faang/assets/icon-list/XvqMI3OqoSa.png',
    w: 8,
    h: 8,
    p: '-13px -1104px',
    sz: 'auto',
  },
  897949: {
    sprited: 2,
    spi: '/faang/assets/icon-list/XvqMI3OqoSa.png',
    _spi: '/faang/assets/icon-list/XvqMI3OqoSa.png',
    w: 8,
    h: 8,
    p: '-13px -1113px',
    sz: 'auto',
  },
  702721: {
    sprited: 2,
    spi: '/faang/assets/icon-list/XvqMI3OqoSa.png',
    _spi: '/faang/assets/icon-list/XvqMI3OqoSa.png',
    w: 8,
    h: 8,
    p: '-13px -1122px',
    sz: 'auto',
  },
  701592: {
    sprited: 2,
    spi: '/faang/assets/icon-list/XvqMI3OqoSa.png',
    _spi: '/faang/assets/icon-list/XvqMI3OqoSa.png',
    w: 8,
    h: 8,
    p: '-13px -1095px',
    sz: 'auto',
  },
};
